from jinja2 import Template
import io
import json
import html
import re
import datetime
from urllib.parse import urlparse
import uuid
import ipaddress
import zipfile
import pandas as pd
import streamlit as st
import altair as alt

from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.chart import BarChart, Reference, Series
from openpyxl.chart.label import DataLabelList
from openpyxl.chart.axis import ChartLines
from openpyxl.chart.layout import Layout, ManualLayout
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

from constants import TLD_INFO, RIR_LINKS
from utils import is_valid_ip, extract_actual_ip, is_valid_domain, is_ipv4

def get_copy_target(ip_display):
    if not ip_display: return ""
    return str(ip_display).split(' - ')[0].split(' ')[0]

# HTMLレポート生成関数
def generate_full_report_html(isp_full_df, country_full_df, freq_full_df):
    
    def create_chunked_chart_specs(df, x_col, y_col, title_base, chunk_size=50):
        specs = []
        # データ全体での最大値を取得 (ページまたぎのスケール統一のため)
        global_max = df[x_col].max() if not df.empty else 0

        # データフレームを分割
        chunks = [df[i:i + chunk_size] for i in range(0, df.shape[0], chunk_size)]
        
        for i, chunk in enumerate(chunks):
            chart_title = f"{title_base} ({i+1}/{len(chunks)})" if len(chunks) > 1 else title_base
            
            # 数値ラベル付きチャート
            # x軸のスケールを全体最大値で固定する
            base = alt.Chart(chunk).encode(
                x=alt.X(x_col, title='Count', scale=alt.Scale(domain=[0, global_max])),
                y=alt.Y(y_col, sort='-x', title=y_col),
                tooltip=[y_col, x_col]
            )
            bars = base.mark_bar()
            text = base.mark_text(
                align='left',
                baseline='middle',
                dx=5, 
                fontSize=11,
                fontWeight='bold'
            ).encode(
                text=x_col
            )
            chart = (bars + text).properties(
                title=chart_title,
                width=700,
                height=alt.Step(20) 
            )
            specs.append(chart.to_dict())
        return specs

    # 各カテゴリのチャートスペックを生成
    target_specs = create_chunked_chart_specs(freq_full_df, 'Count', 'Target_IP', 'Target IP Counts (All)')
    isp_specs = create_chunked_chart_specs(isp_full_df, 'Count', 'ISP', 'ISP Counts (All)')
    country_specs = create_chunked_chart_specs(country_full_df, 'Count', 'Country', 'Country Counts (All)')

    # HTMLテンプレート
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <title>Whois Search Full Report</title>
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body {{ font-family: "Helvetica Neue", Arial, sans-serif; padding: 40px; background-color: #fff; color: #333; }}
        h1 {{ text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }}
        h2 {{ 
            color: #1e3a8a; 
            margin-top: 50px; 
            border-left: 5px solid #1e3a8a; 
            padding-left: 15px; 
            page-break-before: always; 
        }}
        h2:first-of-type {{ page-break-before: auto; }} 
        
        .chart-container {{ 
            margin-bottom: 40px; 
            padding: 10px; 
            page-break-inside: avoid; 
        }}
        
        @media print {{
            body {{ padding: 0; background-color: #fff; }}
            .no-print {{ display: none; }}
            h2 {{ margin-top: 20px; }}
        }}
      </style>
    </head>
    <body>
      <h1>Whois検索結果分析レポート</h1>
      <p style="text-align: center; color: #666;">Generated by Whois Search Tool</p>

      <h2>対象IPアドレス カウント (全 {len(freq_full_df)} 件)</h2>
      <div id="target_charts"></div>

      <h2>ISP別 カウント (全 {len(isp_full_df)} 件)</h2>
      <div id="isp_charts"></div>

      <h2>国別 カウント (全 {len(country_full_df)} 件)</h2>
      <div id="country_charts"></div>

      <script type="text/javascript">
        // Embed charts function
        function embedCharts(containerId, specs) {{
            const container = document.getElementById(containerId);
            specs.forEach((spec, index) => {{
                const div = document.createElement('div');
                div.id = containerId + '_' + index;
                div.className = 'chart-container';
                container.appendChild(div);
                vegaEmbed('#' + div.id, spec, {{actions: false}});
            }});
        }}

        // Data from Python (Serialized to JSON)
        const targetSpecs = {json.dumps(target_specs)};
        const ispSpecs = {json.dumps(isp_specs)};
        const countrySpecs = {json.dumps(country_specs)};

        // Render
        if (targetSpecs.length > 0) embedCharts('target_charts', targetSpecs);
        else document.getElementById('target_charts').innerHTML = '<p>データなし</p>';

        if (ispSpecs.length > 0) embedCharts('isp_charts', ispSpecs);
        else document.getElementById('isp_charts').innerHTML = '<p>データなし</p>';

        if (countrySpecs.length > 0) embedCharts('country_charts', countrySpecs);
        else document.getElementById('country_charts').innerHTML = '<p>データなし</p>';
      </script>
    </body>
    </html>
    """
    return html_template

# --- 🛡️ 脅威インテリジェンス (STIX 2.1) 生成関数 ---
def generate_stix2_bundle(results):
    """ 調査結果をSTIX 2.1形式のBundle (JSON) に変換する """
    objects = []
    # STIXの時刻は UTC の ISO8601 形式が必須
    now_utc = datetime.datetime.now(datetime.timezone.utc)
    now_str = now_utc.strftime('%Y-%m-%dT%H:%M:%S.000Z')

    # 1. ツール自身のIdentity（作成者）オブジェクト
    identity_id = f"identity--{uuid.uuid4()}"
    objects.append({
        "type": "identity",
        "spec_version": "2.1",
        "id": identity_id,
        "created": now_str,
        "modified": now_str,
        "name": "検索大臣 - IP/Domain OSINT Tool",
        "identity_class": "system"
    })

    # 2. 各ターゲットをIndicator（脅威インジケーター）オブジェクトとして変換
    for res in results:
        target = res.get("Target_IP", "")
        if not target or target == "N/A": continue
        
        # 集約モード時の表記 (1.1.1.1 - 1.1.1.5) やドメイン複合 (example.com (1.1.1.1)) をクリーンアップ
        clean_target = str(target).split(' - ')[0].split(' ')[0]
        if "(" in clean_target:
            clean_target = clean_target.split("(")[0].strip()

        # STIXのサイバー観測パターンの構築
        try:
            ip_obj = ipaddress.ip_address(clean_target)
            if ip_obj.version == 4:
                pattern = f"[ipv4-addr:value = '{clean_target}']"
            else:
                pattern = f"[ipv6-addr:value = '{clean_target}']"
        except ValueError:
            pattern = f"[domain-name:value = '{clean_target}']"

        isp = res.get("ISP_JP", "N/A")
        country = res.get("Country_JP", "N/A")
        proxy = res.get("Proxy_Type", "")
        risk = res.get("IoT_Risk", "")

        # 脅威の説明文を構築
        desc = f"【OSINT調査結果】\nISP: {isp}\n国: {country}\n匿名化/クラウド: {proxy if proxy else 'なし'}\nIoTリスク: {risk}"
        
        # SOC向けのアラート用ラベル
        labels = ["osint-target"]
        if proxy and proxy != "未検証" and "Standard" not in proxy: 
            labels.append("anonymization-proxy-vpn")
        if risk and risk not in ["[No Match]", "[Not Checked]", ""]: 
            labels.append("vulnerable-iot")

        indicator_id = f"indicator--{uuid.uuid4()}"
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": indicator_id,
            "created_by_ref": identity_id,
            "created": now_str,
            "modified": now_str,
            "name": f"OSINT Target: {clean_target}",
            "description": desc,
            "indicator_types": ["malicious-activity" if len(labels) > 1 else "anomalous-activity"],
            "pattern": pattern,
            "pattern_type": "stix",
            "valid_from": now_str,
            "labels": labels
        })

    # 3. すべてを1つのBundleにパッキング
    bundle = {
        "type": "bundle",
        "id": f"bundle--{uuid.uuid4()}",
        "objects": objects
    }
    
    return json.dumps(bundle, indent=4, ensure_ascii=False)

# 📈 クロス分析用HTMLレポート生成関数
from jinja2 import Template

def generate_cross_analysis_html(chart_spec, x_col, group_col):
    template_str = """
    <!DOCTYPE html>
    <html>
    <head>
      <title>Whois Cross Analysis Report</title>
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body { font-family: "Helvetica Neue", Arial, sans-serif; padding: 40px; background-color: #fff; color: #333; }
        h1 { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }
        .info { text-align: center; color: #666; margin-bottom: 20px; }
        .chart-container { 
            width: 100%; 
            display: flex; 
            justify-content: center; 
            margin-bottom: 40px; 
            padding: 10px; 
        }
      </style>
    </head>
    <body>
      <!-- 変数の展開と自動HTMLエスケープ (| e) -->
      <h1>クロス分析レポート: {{ x_col | e }} vs {{ group_col | e }}</h1>
      <p class="info">Generated by Whois Search Tool</p>

      <div id="chart" class="chart-container"></div>

      <script type="text/javascript">
        // JSONデータを安全に埋め込み
        const spec = {{ chart_spec_json | safe }};
        vegaEmbed('#chart', spec, {actions: true});
      </script>
    </body>
    </html>
    """
    template = Template(template_str)
    # テンプレートに変数を渡してレンダリング
    return template.render(
        chart_spec_json=json.dumps(chart_spec), 
        x_col=x_col, 
        group_col=group_col
    )

def generate_full_report_html(isp_full_df, country_full_df, freq_full_df):
    # (前半の create_chunked_chart_specs などはそのまま)
    def create_chunked_chart_specs(df, x_col, y_col, title_base, chunk_size=50):
        specs = []
        global_max = df[x_col].max() if not df.empty else 0
        chunks = [df[i:i + chunk_size] for i in range(0, df.shape[0], chunk_size)]
        
        for i, chunk in enumerate(chunks):
            chart_title = f"{title_base} ({i+1}/{len(chunks)})" if len(chunks) > 1 else title_base
            base = alt.Chart(chunk).encode(
                x=alt.X(x_col, title='Count', scale=alt.Scale(domain=[0, global_max])),
                y=alt.Y(y_col, sort='-x', title=y_col),
                tooltip=[y_col, x_col]
            )
            bars = base.mark_bar()
            text = base.mark_text(align='left', baseline='middle', dx=5, fontSize=11, fontWeight='bold').encode(text=x_col)
            chart = (bars + text).properties(title=chart_title, width=700, height=alt.Step(20))
            specs.append(chart.to_dict())
        return specs

    target_specs = create_chunked_chart_specs(freq_full_df, 'Count', 'Target_IP', 'Target IP Counts (All)')
    isp_specs = create_chunked_chart_specs(isp_full_df, 'Count', 'ISP', 'ISP Counts (All)')
    country_specs = create_chunked_chart_specs(country_full_df, 'Count', 'Country', 'Country Counts (All)')

    template_str = """
    <!DOCTYPE html>
    <html>
    <head>
      <title>Whois Search Full Report</title>
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body { font-family: "Helvetica Neue", Arial, sans-serif; padding: 40px; background-color: #fff; color: #333; }
        h1 { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }
        h2 { color: #1e3a8a; margin-top: 50px; border-left: 5px solid #1e3a8a; padding-left: 15px; page-break-before: always; }
        h2:first-of-type { page-break-before: auto; } 
        .chart-container { margin-bottom: 40px; padding: 10px; page-break-inside: avoid; }
        @media print {
            body { padding: 0; background-color: #fff; }
            .no-print { display: none; }
            h2 { margin-top: 20px; }
        }
      </style>
    </head>
    <body>
      <h1>Whois検索結果分析レポート</h1>
      <p style="text-align: center; color: #666;">Generated by Whois Search Tool</p>

      <h2>対象IPアドレス カウント (全 {{ target_count }} 件)</h2>
      <div id="target_charts"></div>

      <h2>ISP別 カウント (全 {{ isp_count }} 件)</h2>
      <div id="isp_charts"></div>

      <h2>国別 カウント (全 {{ country_count }} 件)</h2>
      <div id="country_charts"></div>

      <script type="text/javascript">
        function embedCharts(containerId, specs) {
            const container = document.getElementById(containerId);
            specs.forEach((spec, index) => {
                const div = document.createElement('div');
                div.id = containerId + '_' + index;
                div.className = 'chart-container';
                container.appendChild(div);
                vegaEmbed('#' + div.id, spec, {actions: false});
            });
        }

        const targetSpecs = {{ target_specs_json | safe }};
        const ispSpecs = {{ isp_specs_json | safe }};
        const countrySpecs = {{ country_specs_json | safe }};

        if (targetSpecs.length > 0) embedCharts('target_charts', targetSpecs);
        else document.getElementById('target_charts').innerHTML = '<p>データなし</p>';

        if (ispSpecs.length > 0) embedCharts('isp_charts', ispSpecs);
        else document.getElementById('isp_charts').innerHTML = '<p>データなし</p>';

        if (countrySpecs.length > 0) embedCharts('country_charts', countrySpecs);
        else document.getElementById('country_charts').innerHTML = '<p>データなし</p>';
      </script>
    </body>
    </html>
    """
    
    template = Template(template_str)
    return template.render(
        target_count=len(freq_full_df),
        isp_count=len(isp_full_df),
        country_count=len(country_full_df),
        target_specs_json=json.dumps(target_specs),
        isp_specs_json=json.dumps(isp_specs),
        country_specs_json=json.dumps(country_specs)
    )
# --- Excel生成ヘルパー関数 ---
def convert_df_to_excel(df):
    output = io.BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Sheet1')
    return output.getvalue()

# --- Advanced Excel Generator (Pivot & Chart) ---
def create_advanced_excel(df, time_col_name=None):
    output = io.BytesIO()
    
    # 1. IPアドレスが含まれているかを判定 (すべての列を検査してIP列を正確に特定する)
    target_col = 'IPアドレス' if 'IPアドレス' in df.columns else ('Target_IP' if 'Target_IP' in df.columns else df.columns[0])
    has_ip = False
    for col in df.columns:
        # 最初の数行をチェックしてIPアドレスを含む列を探す
        if any(is_valid_ip(str(val)) for val in df[col].dropna().head(20)):
            has_ip = True
            target_col = col
            break
    
    # ==========================================
    # パターンA: すべてドメイン(非IP)の場合
    # ==========================================
    if not has_ip:
        if target_col in df.columns:
            df = df.rename(columns={target_col: 'Target Domain'})
        # 不要な列を削除（統一した列名に対応）
        cols_to_drop = ['Whois(元データ)', 'Whois(日本語名)', '国名（英語）', '国名', 'プロキシ種別', 'ステータス', 'IoTリスク', 'RDAP(元データ)', 'RDAP(日本語名)', 'ISP', 'ISP_JP', 'Country', 'Country_JP']
        df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors='ignore')
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Domain Results')
        return output.getvalue()

    # ==========================================
    # パターンB: IPアドレスが含まれる場合 (分析グラフ付き)
    # ==========================================
    # 必須カラムの補完 (統一した列名を基準にする)
    required_cols = {
        'プロキシ種別': '',
        'Whois(日本語名)': 'N/A',
        '国名': 'N/A'
    }
    for col, default_val in required_cols.items():
        if col not in df.columns:
            df[col] = default_val

    # データ前処理：空欄や欠損値を空文字（何もなし）に統一
    df['プロキシ種別'] = df['プロキシ種別'].fillna('')
    
    # --- プロキシ種別の表記簡略化 (Excel出力専用) ---
    def clean_proxy_text(text):
        if not text or pd.isna(text): return "未検証"
        t = str(text)
        # "(Source: ...)" などの情報元表記を削除
        t = re.sub(r'\s*\((Source:|API Verified|Local DB)[^)]*\)', '', t)
        # "API Confirmed (VPN)" -> "VPN" のように抽出
        t = re.sub(r'API Confirmed \((.*?)\)', r'\1', t)
        # "[VPN/PROXY]" -> "VPN/PROXY" のようにブラケットを外す
        t = re.sub(r'\[(.*?)\]', r'\1', t)
        t = t.strip(' /')
        return t if t else "未検証"
        
    if 'プロキシ種別' in df.columns:
        df['プロキシ種別'] = df['プロキシ種別'].apply(clean_proxy_text)
    
    has_time_analysis = False
    if time_col_name and time_col_name in df.columns:
        try:
            df['Hour'] = pd.to_datetime(df[time_col_name], errors='coerce').dt.hour
            has_time_analysis = True
        except Exception:
            pass

    count_col = df.columns[0]

    # 書き込み開始
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Raw Data')
        wb = writer.book
        
        def add_chart_sheet(pivot_df, sheet_name, chart_title, x_title, y_title, description, chart_type="col", stacked=False):
            if pivot_df.empty: return
            pivot_df.to_excel(writer, sheet_name=sheet_name, startrow=4)
            ws = wb[sheet_name]
            ws['A1'] = chart_title
            ws['A1'].font = Font(size=14, bold=True, color="1E3A8A")
            ws['A2'] = description
            ws['A2'].font = Font(size=11, color="555555", italic=True)
            ws['A2'].alignment = Alignment(wrap_text=True, vertical="top")
            ws.merge_cells('A2:H3')
            
            chart = BarChart()
            chart.type = chart_type
            chart.style = 10 
            chart.title = chart_title
            chart.height = 15 
            chart.width = 25  
            # 凡例を非表示にする
            chart.legend = None
            
            if stacked:
                chart.grouping = "stacked"
                chart.overlap = 100
            else:
                chart.varyColors = True
                
            chart.dataLabels = DataLabelList()
            chart.dataLabels.showVal = True
                
            chart.x_axis.title = x_title
            chart.y_axis.title = y_title
            chart.y_axis.majorGridlines = ChartLines() 
            chart.y_axis.delete = False        
            chart.y_axis.numFmt = '0'          
            chart.y_axis.majorTickMark = 'out' 
            chart.y_axis.tickLblPos = 'nextTo' 
            chart.layout = Layout(manualLayout=ManualLayout(x=0.03, y=0.05, h=0.75, w=0.85))
            
            data_start_row = 5 
            data_end_row = data_start_row + len(pivot_df)
            data = Reference(ws, min_col=2, min_row=data_start_row, max_row=data_end_row, max_col=len(pivot_df.columns)+1)
            cats = Reference(ws, min_col=1, min_row=data_start_row+1, max_row=data_end_row)
            chart.add_data(data, titles_from_data=True)
            chart.set_categories(cats)
            ws.add_chart(chart, "E5")

        # プロキシデータが有効か（全て空文字ではないか）を判定するフラグ
        proxy_col = 'プロキシ種別'
        has_valid_risk_data = False
        if proxy_col in df.columns:
            if not (df[proxy_col] == '').all():
                has_valid_risk_data = True

        # 1. Report_Whois_Volume: ISP別アクセス数
        isp_col = 'Whois(日本語名)'
        if isp_col in df.columns and not (df[isp_col] == 'N/A').all():
            top_isps = df[isp_col].value_counts().head(20).index
            df_isp = df[df[isp_col].isin(top_isps)]
            pivot_isp_vol = df_isp.pivot_table(index=isp_col, values=count_col, aggfunc='count')
            
            if not pivot_isp_vol.empty:
                pivot_isp_vol = pivot_isp_vol.sort_values(count_col, ascending=False)
                desc_isp_vol = "どの組織・プロバイダからのアクセスが最も多いかを可視化しています。特定のISPからのアクセス集中は、そのサービスの利用者層または特定のキャンペーンの影響を示唆します。"
                add_chart_sheet(pivot_isp_vol, 'Report_Whois_Volume', 'Whois Access Volume Ranking (Top 20)', 'ISP Name', 'Count', desc_isp_vol)

            # 2. Report_Whois_Risk: ISP別リスク分析
            if has_valid_risk_data:
                pivot_isp_risk = df_isp.pivot_table(index=isp_col, columns=proxy_col, values=count_col, aggfunc='count', fill_value=0)
                if not pivot_isp_risk.empty:
                    desc_isp_risk = "そのISPが安全な一般回線か、注意が必要なサーバー/VPN経由かを判定しています。「未検証」はAPIによる検証なし、「Standard Connection (API Verified)」はAPI検証済みの一般回線を示します。"
                    add_chart_sheet(pivot_isp_risk, 'Report_Whois_Risk', 'Risk Analysis by Whois (Top 20)', 'ISP Name', 'Count', desc_isp_risk, stacked=True)

        # 3. Report_RDAP_Volume: RDAP別アクセス数
        rdap_col = 'RDAP(日本語名)'
        if rdap_col in df.columns:
            df[rdap_col] = df[rdap_col].replace('', 'N/A')
            
            if not (df[rdap_col] == 'N/A').all():
                top_rdaps = df[rdap_col].value_counts().head(20).index
                df_rdap = df[df[rdap_col].isin(top_rdaps)]
                pivot_rdap_vol = df_rdap.pivot_table(index=rdap_col, values=count_col, aggfunc='count')
                
                if not pivot_rdap_vol.empty:
                    pivot_rdap_vol = pivot_rdap_vol.sort_values(count_col, ascending=False)
                    desc_rdap_vol = "公式レジストリ（RDAP）に登録されている法的な保有組織ごとのアクセス数です。Whois（運用者）とは異なる、IPアドレスブロックの真の所有者傾向を可視化します。"
                    add_chart_sheet(pivot_rdap_vol, 'Report_RDAP_Volume', 'RDAP Access Volume Ranking (Top 20)', 'RDAP Name', 'Count', desc_rdap_vol)

                # 4. Report_RDAP_Risk: RDAP別リスク分析
                if has_valid_risk_data:
                    pivot_rdap_risk = df_rdap.pivot_table(index=rdap_col, columns=proxy_col, values=count_col, aggfunc='count', fill_value=0)
                    if not pivot_rdap_risk.empty:
                        desc_rdap_risk = "法的保有組織（RDAP）ごとの接続環境を分析しています。特定の組織が保有するIP帯域が、プロキシやVPNインフラとして集中的に悪用されていないかを確認できます。"
                        add_chart_sheet(pivot_rdap_risk, 'Report_RDAP_Risk', 'Risk Analysis by RDAP (Top 20)', 'RDAP Name', 'Count', desc_rdap_risk, stacked=True)
        
        # 5. Report_Country: 国別アクセス数
        if '国名' in df.columns and not (df['国名'] == 'N/A').all():
            pivot_country = df.pivot_table(index='国名', values=count_col, aggfunc='count')
            if not pivot_country.empty:
                pivot_country = pivot_country.sort_values(count_col, ascending=False).head(15)
                desc_country = "国ごとのアクセス数をランキング化しています。サービス提供エリア外からの予期せぬアクセス検知や、海外からの攻撃予兆の発見に役立ちます。"
                add_chart_sheet(pivot_country, 'Report_Country', 'Country Access Volume (Top 15)', 'Country Name', 'Count', desc_country)

        # 6. Report_Time: 時間帯分析
        if has_time_analysis:
            pivot_time_vol = df.pivot_table(index='Hour', values=count_col, aggfunc='count', fill_value=0).reindex(range(24), fill_value=0)
            desc_time_vol = "何時にアクセスが集中しているかを可視化しています。一般的なユーザーは活動時間帯に、Botなどは深夜早朝や24時間一定のアクセスを行う傾向があります。"
            add_chart_sheet(pivot_time_vol, 'Report_Time_Volume', 'Hourly Access Trend', 'Hour (0-23h)', 'Count', desc_time_vol)

            if has_valid_risk_data:
                pivot_time_risk = df.pivot_table(index='Hour', columns=proxy_col, values=count_col, aggfunc='count', fill_value=0).reindex(range(24), fill_value=0)
                desc_time_risk = "深夜帯などに怪しいアクセス（Hosting/VPN等）が増えていないかを確認できます。夜間にHosting判定が増加する場合、Botによる自動巡回の可能性があります。"
                add_chart_sheet(pivot_time_risk, 'Report_Time_Risk', 'Hourly Risk Trend', 'Hour (0-23h)', 'Count', desc_time_risk, stacked=True)
            
    return output.getvalue()

def _safe_highlight_json(json_obj, key_patterns=None, val_matches=None):
    """JSON文字列を生成し、安全にHTMLエスケープした上で特定のキー/値をハイライトするヘルパー"""
    if not json_obj: return ""
    # 辞書をJSON文字列化し、全体を安全にエスケープ
    escaped = html.escape(json.dumps(json_obj, indent=4, ensure_ascii=False))
    
    if key_patterns:
        for kp in key_patterns:
            # 汎用的なJSONキーのハイライト (&quot;key&quot;:)
            escaped = re.sub(r'(&quot;' + kp + r'&quot;\s*:)', r'<span class="json-hl">\1</span>', escaped)
            
    if val_matches:
        for val in val_matches:
            if val and val != "情報なし":
                esc_val = html.escape(str(val))
                escaped = escaped.replace(f'&quot;{esc_val}&quot;', f'<span class="json-hl">&quot;{esc_val}&quot;</span>')
                
    return escaped

def generate_individual_html_report(res, clean_ip, report_opts=None, resolved_dns_map=None):
    """
    個別IPの詳細HTMLレポートを生成する (Jinja2 テンプレートエンジン適用版)
    """
    if resolved_dns_map is None: resolved_dns_map = {}
    if report_opts is None:
        report_opts = {"tld": True, "dns": True, "subnet": True, "rdap": True, "whois": True, "ipinfo": True, "vpnapi": True, "st": True, "rdns": True, "revip": True}
    
    # ---------------------------------------------------------
    # 1. データの抽出と成形 (Python ロジック層)
    # ---------------------------------------------------------
    target_ip = res.get('Target_IP', 'N/A')
    is_composite = ("(" in target_ip and ")" in target_ip)
    
    # ドメイン名の特定
    domain_name = ""
    if is_composite:
        domain_name = target_ip.split("(")[0].strip()
    elif not is_valid_ip(target_ip): 
        domain_name = target_ip
        
    nslookup_data = resolved_dns_map.get(domain_name, {}) if domain_name else {}
    nslookup_raw = nslookup_data.get('raw', '') if isinstance(nslookup_data, dict) else (nslookup_data if isinstance(nslookup_data, str) else "")
    nslookup_ips = nslookup_data.get('ips', []) if isinstance(nslookup_data, dict) else []

    rdns_data = res.get('RDNS_DATA', {})
    rdns_raw = rdns_data.get('raw', '') if isinstance(rdns_data, dict) else ""
    rdns_hosts = rdns_data.get('hosts', []) if isinstance(rdns_data, dict) else []

    proxy_info = res.get('Proxy_Type', 'Standard Connection')
    proxy_source_match = re.search(r'\((Source:.*?)\)', proxy_info)
    
    iot_risk = res.get('IoT_Risk', '[Not Checked]')
    threat_source_match = re.search(r'\((Source:.*?)\)', iot_risk)

    has_proxy_alert = bool(proxy_info and proxy_info not in ["Standard Connection", "N/A (Domain)", "N/A", "未検証"])

    # レポート生成の必要性判定
    if not (res.get('RDAP_JSON') or res.get('IPINFO_JSON') or res.get('DOMAIN_RDAP_JSON') or 
            res.get('DOMAIN_WHOIS_TEXT') or nslookup_raw or res.get('ST_JSON') or 
            rdns_raw or res.get('IP_WHOIS_TEXT') or 
            res.get('ST_REVERSE_IP_JSON') or has_proxy_alert):
        return None 

    jst_timezone = datetime.timezone(datetime.timedelta(hours=9))
    current_time_str = datetime.datetime.now(jst_timezone).strftime("%Y年%m月%d日 %H時%M分")

    # Jinja2に渡すコンテキスト辞書
    ctx = {
        'clean_ip': clean_ip,
        'target_ip': target_ip,
        'domain_name': domain_name,
        'current_time': current_time_str,
        'opts': report_opts,
        
        # Attribution
        'proxy_info': proxy_info,
        'proxy_source': proxy_source_match.group(1) if proxy_source_match else "Dynamic/API",
        'iot_risk': iot_risk,
        'threat_source': threat_source_match.group(1) if threat_source_match else "External Intelligence",
        
        # Flags for tabs
        'show_subnet': False,
        'show_nslookup': bool(nslookup_raw and report_opts.get("dns", True)),
        'show_tld': bool(domain_name and report_opts.get("tld", True)),
        'show_domain_rdap': bool(res.get('DOMAIN_RDAP_JSON') and report_opts.get("rdap", True)),
        'show_domain_whois': bool(res.get('DOMAIN_WHOIS_TEXT') and report_opts.get("whois", True)),
        'show_ip_rdap': bool(res.get('RDAP_JSON') and report_opts.get("rdap", True)),
        'show_ip_whois': bool(res.get('IP_WHOIS_TEXT') and report_opts.get("whois", True)),
        'show_ipinfo': bool(res.get('IPINFO_JSON') and report_opts.get("ipinfo", True)),
        'show_vpnapi': bool((res.get('VPNAPI_JSON') or has_proxy_alert) and report_opts.get("vpnapi", True)),
        'show_st_history': bool(res.get('ST_JSON') and report_opts.get("st", True)),
        'show_st_revip': bool(res.get('ST_REVERSE_IP_JSON') and report_opts.get("revip", True)),
        'show_rdns': bool(rdns_raw and report_opts.get("rdns", True)),
    }

    # --- Subnet Data ---
    if ctx['show_ip_rdap']:
        rdap_json = res['RDAP_JSON']
        try:
            ip_obj = ipaddress.ip_address(clean_ip)
            if "startAddress" in rdap_json and "endAddress" in rdap_json and report_opts.get("rdap", False):
                s_ip = ipaddress.ip_address(rdap_json["startAddress"])
                e_ip = ipaddress.ip_address(rdap_json["endAddress"])
                target_net = next((cidr for cidr in ipaddress.summarize_address_range(s_ip, e_ip) if ip_obj in cidr), None)
                
                if target_net:
                    ctx['show_subnet'] = True
                    ctx['subnet'] = {'version': ip_obj.version, 'prefix': target_net.prefixlen, 'network_addr': str(target_net.network_address)}
                    if ip_obj.version == 4:
                        first_octet = int(str(ip_obj).split('.')[0])
                        ctx['subnet']['class'] = "クラスA" if 1 <= first_octet <= 126 else ("クラスB" if 128 <= first_octet <= 191 else ("クラスC" if 192 <= first_octet <= 223 else "その他"))
                        ctx['subnet']['netmask'] = str(target_net.netmask)
                        ctx['subnet']['host_min'] = str(target_net[1]) if target_net.num_addresses > 2 else "なし"
                        ctx['subnet']['host_max'] = str(target_net[-2]) if target_net.num_addresses > 2 else "なし"
                        ctx['subnet']['broadcast_addr'] = str(target_net.broadcast_address)
                        ctx['subnet']['num_hosts'] = max(0, target_net.num_addresses - 2)
                        ctx['subnet']['total_ips'] = target_net.num_addresses
                    else:
                        ctx['subnet']['last_addr'] = str(target_net.broadcast_address)
                        ctx['subnet']['total_ips'] = target_net.num_addresses
                        p = target_net.prefixlen
                        ctx['subnet']['scope'] = "大規模ISP割当" if p <= 32 else ("企業拠点" if p <= 48 else "単一セグメント等")
        except ValueError: pass

    # --- DNS/nslookup Data ---
    if ctx['show_nslookup']:
        escaped_nslookup = html.escape(nslookup_raw)
        for ip_str in nslookup_ips:
            escaped_nslookup = escaped_nslookup.replace(html.escape(ip_str), f'<span class="json-hl">{html.escape(ip_str)}</span>')
        ctx['ns'] = {
            'ips': "<br>".join([html.escape(ip) for ip in nslookup_ips]) if nslookup_ips else "取得なし",
            'raw': escaped_nslookup,
            'cmd': f"resolver.resolve('{domain_name}', 'A/AAAA/MX')",
            'disposables': res.get('DISPOSABLE_SERVICES', [])
        }

    # --- TLD Data ---
    if ctx['show_tld']:
        tld_val = domain_name.split('.')[-1].lower() if '.' in domain_name else ""
        tld_data = TLD_INFO.get(tld_val, {"name": "その他の国・地域 / gTLD", "jp_name": "未分類", "url": ""})
        ctx['tld'] = {
            'ext': tld_val,
            'jp_name': tld_data['jp_name'],
            'name': tld_data['name'],
            'url': tld_data['url'] if tld_data['url'] != "N/A" else "",
            'iana': f"https://www.iana.org/domains/root/db/{tld_val}.html" if tld_val else ""
        }

    # --- Domain RDAP ---
    if ctx['show_domain_rdap']:
        d_json = res['DOMAIN_RDAP_JSON']
        reg_date, exp_date, registrar, registrant = "情報なし", "情報なし", "情報なし", "情報なし"
        for ev in d_json.get("events", []):
            if ev.get("eventAction") == "registration": reg_date = ev.get("eventDate", "情報なし")
            elif ev.get("eventAction") == "expiration": exp_date = ev.get("eventDate", "情報なし")
        for ent in d_json.get("entities", []):
            roles = ent.get("roles", [])
            for vcard in ent.get("vcardArray", [[]])[1] if len(ent.get("vcardArray", [])) > 1 else []:
                if "registrar" in roles and vcard[0] == "fn": registrar = vcard[3]
                if "registrant" in roles and vcard[0] in ["org", "fn"]: registrant = vcard[3]
                
        ns_list = [ns.get("ldhName") for ns in d_json.get("nameservers", []) if ns.get("ldhName")]
        ctx['d_rdap'] = {
            'url': res['DOMAIN_RDAP_URL'],
            'registry': urlparse(res['DOMAIN_RDAP_URL']).netloc,
            'registrar': registrar, 'registrant': registrant,
            'reg_date': reg_date, 'exp_date': exp_date,
            'ns_html': "<br>".join(ns_list) if ns_list else "情報なし",
            'raw': _safe_highlight_json(d_json, ['registrar', 'registrant', 'registration', 'expiration', 'nameservers'], [registrar, registrant, reg_date, exp_date])
        }

    # --- Domain WHOIS ---
    if ctx['show_domain_whois']:
        ctx['d_whois'] = {
            'server': res['DOMAIN_WHOIS_SERVER'],
            'raw': html.escape(str(res['DOMAIN_WHOIS_TEXT']))
        }

    # --- IP RDAP ---
    if ctx['show_ip_rdap']:
        i_json = res['RDAP_JSON']
        actual_url = res['RDAP_URL']
        for link in i_json.get("links", []):
            if link.get("rel") == "self": actual_url = link.get("href", actual_url); break
            
        descs = []
        for remark in i_json.get("remarks", []):
            d = remark.get("description", [])
            if isinstance(d, list): descs.extend(d)
            elif isinstance(d, str): descs.append(d)
            
        ctx['i_rdap'] = {
            'url': actual_url,
            'registry': urlparse(actual_url).netloc,
            'name': i_json.get("name", "情報なし"),
            'country': "JP (Japan)" if i_json.get("country") == "JP" else ("US (United States)" if i_json.get("country") == "US" else i_json.get("country", "情報なし")),
            'start': i_json.get("startAddress", "情報なし"),
            'end': i_json.get("endAddress", "情報なし"),
            'remarks': "<br>".join(descs) if descs else "",
            'raw': _safe_highlight_json(i_json, ['name', 'country', 'startAddress', 'endAddress', 'remarks', 'description'], descs)
        }

    # --- IP WHOIS ---
    if ctx['show_ip_whois']:
        ctx['i_whois'] = {
            'server': res['IP_WHOIS_SERVER'],
            'raw': html.escape(str(res['IP_WHOIS_TEXT']))
        }

    # --- IPinfo ---
    if ctx['show_ipinfo']:
        info = res['IPINFO_JSON']
        ip_val = info.get("ip", clean_ip)
        flags = [k.capitalize() for k in ["vpn", "proxy", "tor", "relay", "hosting"] if info.get("privacy", {}).get(k)]
        ctx['ipinfo'] = {
            'ip': ip_val,
            'req_url': f"https://ipinfo.io/{ip_val}",
            'hostname': info.get("hostname", "情報なし"),
            'org': info.get("org", "情報なし"),
            'region': f"{info.get('country', '')}, {info.get('region', '')}, {info.get('city', '')}".strip(', '),
            'loc': info.get("loc", "情報なし"),
            'map_url': f"https://maps.google.com/maps?q={info.get('loc')}&hl=ja&z=14&output=embed" if "," in info.get("loc", "") else "",
            'privacy': ", ".join(flags) if flags else "",
            'raw': _safe_highlight_json(info, ['ip', 'hostname', 'city', 'region', 'country', 'loc', 'org'])
        }

    # --- VPNAPI ---
    if ctx['show_vpnapi']:
        v_json = res.get('VPNAPI_JSON')
        if v_json:
            sec = v_json.get('security') or {}
            detected = [k.upper() for k, v in sec.items() if v]
            ctx['vpnapi'] = {
                'has_api': True,
                'req_ip': v_json.get('ip', clean_ip),
                'status_text': "該当あり (匿名通信検知)" if detected else "該当なし",
                'status_color': "red" if detected else "green",
                'types': " / ".join(detected) if detected else "情報なし",
                'org': (v_json.get('network') or {}).get('autonomous_system_organization', '情報なし'),
                'country': (v_json.get('location') or {}).get('country', '情報なし'),
                'raw': _safe_highlight_json(v_json, ['vpn', 'proxy', 'tor', 'relay', 'country', 'ip', 'autonomous_system_organization'])
            }
        else:
            ctx['vpnapi'] = {'has_api': False, 'req_ip': clean_ip}
            
        ctx['vpnapi']['comp_color'] = "#c62828" if has_proxy_alert else "#2e7d32"
        ctx['vpnapi']['comp_text'] = "検知あり (不審・匿名化インフラ等)" if has_proxy_alert else "検知なし (Standard Connection)"

    # --- SecurityTrails (History) ---
    if ctx['show_st_history']:
        st_json = res['ST_JSON']
        ctx['st'] = {
            'is_error': st_json.get('error') == 'rate_limit',
            'records': st_json.get('records', []),
            'filtered': st_json.get('is_date_filtered', False),
            'start': st_json.get('start_date', ''),
            'end': st_json.get('end_date', ''),
            'raw': _safe_highlight_json(st_json, ['ip'])
        }
        if not ctx['st']['is_error']:
            seen = set()
            ctx['st']['unique_ips'] = []
            for rec in ctx['st']['records']:
                for v in rec.get('values', []):
                    if v.get('ip') and v.get('ip') not in seen:
                        seen.add(v.get('ip'))
                        ctx['st']['unique_ips'].append(v.get('ip'))

    # --- Reverse IP ---
    if ctx['show_st_revip']:
        rev_json = res['ST_REVERSE_IP_JSON']
        ctx['revip'] = {
            'is_error': rev_json.get('error') == 'rate_limit',
            'is_partial': rev_json.get('error') == 'rate_limit_during_pagination',
            'records': [r.get('hostname') for r in rev_json.get('records', []) if r.get('hostname')],
            'total': rev_json.get('meta', {}).get('total_records', len(rev_json.get('records', []))),
            'pages': rev_json.get('meta', {}).get('total_pages', 1),
            'source': rev_json.get('source', 'SecurityTrails'),
            'raw': _safe_highlight_json(rev_json, ['hostname'])
        }

    # --- rDNS ---
    if ctx['show_rdns']:
        esc_raw = html.escape(rdns_raw)
        for h in rdns_hosts:
            esc_raw = esc_raw.replace(html.escape(h), f'<span class="json-hl">{html.escape(h)}</span>')
        ctx['rdns'] = {
            'hosts': "<br>".join([html.escape(h) for h in rdns_hosts]) if rdns_hosts else "取得なし",
            'raw': esc_raw
        }

    # ---------------------------------------------------------
    # 2. Jinja2 テンプレート (HTML層)
    # ---------------------------------------------------------
    template_str = """
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>IP-OSINT - {{ clean_ip | e }}</title>
        <style>
            body { font-family: 'Helvetica Neue', Arial, sans-serif; padding: 30px; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; }
            .tab-container { margin-bottom: 20px; border-bottom: 2px solid #ccc; display: flex; }
            .tab-button { background-color: #f8f9fa; border: 1px solid #ccc; border-bottom: none; outline: none; cursor: pointer; padding: 10px 20px; font-size: 16px; font-weight: bold; color: #555; border-radius: 5px 5px 0 0; margin-right: 5px; transition: 0.3s; }
            .tab-button:hover { background-color: #e9ecef; }
            .tab-button.active { background-color: #1e3a8a; color: white; border-color: #1e3a8a; }
            .tab-content { display: none; animation: fadeEffect 0.4s; }
            @keyframes fadeEffect { from {opacity: 0;} to {opacity: 1;} }
            h1 { font-size: 24px; border-bottom: 2px solid; padding-bottom: 5px; text-align: center; margin-bottom: 30px;}
            h1.theme-rdap { color: #1e3a8a; border-color: #1e3a8a; }
            h1.theme-ipinfo { color: #00897b; border-color: #00897b; }
            h1.theme-ip2proxy { color: #6a1b9a; border-color: #6a1b9a; }
            h2 { font-size: 18px; margin-top: 30px; border-left: 4px solid #666; padding-left: 10px; }
            .description { background-color: #f8f9fa; padding: 15px; border-radius: 5px; border: 1px solid #e9ecef; margin-bottom: 20px; font-size: 14px; text-align: justify; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 14px; vertical-align: top; }
            th { background-color: #f2f2f2; width: 30%; }
            .help-text { font-size: 12px; color: #666; display: block; margin-top: 4px; line-height: 1.4; }
            .raw-data { font-family: monospace; background-color: #f4f4f4; padding: 15px; border-radius: 5px; white-space: pre-wrap; font-size: 12px; border: 1px solid #ccc; word-break: break-all; }
            .json-hl { background-color: #fff59d; color: #c62828; font-weight: bold; border-radius: 2px; padding: 1px 3px; transition: 0.3s; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            body.hide-hl .json-hl { background-color: transparent; color: inherit; font-weight: normal; padding: 0; }
            body.hide-desc .description, body.hide-desc .help-text { display: none; }
            body.compress-json .raw-data { white-space: normal; word-break: break-all; }
            .controls { margin-bottom: 20px; text-align: right; background: #e3f2fd; padding: 10px; border-radius: 5px; border: 1px solid #bbdefb; }
            .controls label { font-size: 14px; cursor: pointer; font-weight: bold; color: #1565c0; margin-right: 15px; display: inline-block; margin-bottom: 5px; }
            .controls button { padding: 8px 16px; font-size: 14px; cursor: pointer; background-color: #1e3a8a; color: white; border: none; border-radius: 3px; transition: background 0.3s; margin-top: 5px; }
            .controls button:hover { background-color: #1565c0; }
            @media print {
                body { padding: 0; max-width: 100%; }
                .no-print, .tab-container { display: none !important; }
                .tab-content { display: block !important; page-break-after: always; }
                .tab-content:last-child { page-break-after: auto; }
                .raw-data { page-break-inside: auto; }
                .map-container iframe { width: 100% !important; }
            }
        </style>
    </head>
    <body>
        <div class="controls no-print">
            <div>
                <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-desc', !this.checked)"> 解説・ヘルプテキストを表示</label>
                <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-hl', !this.checked)"> JSONのハイライトを有効化</label>
                <label><input type="checkbox" onchange="document.body.classList.toggle('compress-json', this.checked)"> 生データ(JSON)を圧縮表示</label>
            </div>
            <button onclick="window.print()">🖨️ すべての情報を一括印刷</button>
        </div>
        
        <!-- タブメニュー -->
        <div class="tab-container no-print">
            <button class="tab-button active" onclick="openTab(event, 'tab-overview')" id="btn-tab-overview">概要・判定根拠</button>
            {% if show_subnet %}<button class="tab-button" onclick="openTab(event, 'tab-subnet')" id="btn-tab-subnet">サブネット情報</button>{% endif %}
            {% if show_nslookup %}<button class="tab-button" onclick="openTab(event, 'tab-nslookup')" id="btn-tab-nslookup">DNS正引き</button>{% endif %}
            {% if show_tld %}<button class="tab-button" onclick="openTab(event, 'tab-domain-info')" id="btn-tab-domain-info">ドメイン情報</button>{% endif %}
            {% if show_domain_rdap %}<button class="tab-button" onclick="openTab(event, 'tab-domain-rdap')" id="btn-tab-domain-rdap">RDAP(Domain)</button>{% endif %}
            {% if show_domain_whois %}<button class="tab-button" onclick="openTab(event, 'tab-domain-whois')" id="btn-tab-domain-whois">WHOIS(Domain)</button>{% endif %}
            {% if show_ip_rdap %}<button class="tab-button" onclick="openTab(event, 'tab-rdap')" id="btn-tab-rdap">RDAP(IP)</button>{% endif %}
            {% if show_ip_whois %}<button class="tab-button" onclick="openTab(event, 'tab-ip-whois')" id="btn-tab-ip-whois">WHOIS(IP)</button>{% endif %}
            {% if show_ipinfo %}<button class="tab-button" onclick="openTab(event, 'tab-ipinfo')" id="btn-tab-ipinfo">IPinfo</button>{% endif %}
            {% if show_vpnapi %}<button class="tab-button" onclick="openTab(event, 'tab-vpnapi')" id="btn-tab-vpnapi">匿名通信判定</button>{% endif %}
            {% if show_st_history %}<button class="tab-button" onclick="openTab(event, 'tab-st')" id="btn-tab-st">SecurityTrails</button>{% endif %}
            {% if show_st_revip %}<button class="tab-button" onclick="openTab(event, 'tab-st-revip')" id="btn-tab-st-revip">Reverse IP</button>{% endif %}
            {% if show_rdns %}<button class="tab-button" onclick="openTab(event, 'tab-rdns')" id="btn-tab-rdns">逆引き(rDNS)</button>{% endif %}
        </div>

        <!-- 1. 概要・判定根拠 -->
        <div id="tab-overview" class="tab-content" style="display: block;">
            <h1 style="color: #d84315; border-bottom: 2px solid #d84315;">調査対象: {{ clean_ip | e }}</h1>
            <div class="description" style="background-color: #fff9c4; border-color: #fbc02d;">
                このタブでは、対象に対する各種検知ロジックの総合判定結果（サマリー）を表示しています。
            </div>
            <div class="attribution-box" style="background-color: #fff3e0; padding: 15px; border-radius: 5px; border: 1px solid #ffe0b2; margin-bottom: 20px;">
                <h2 style="margin-top: 0; color: #d84315; border-left: 4px solid #d84315; padding-left: 10px; font-size: 18px;">📊 判定根拠 (Attribution)</h2>
                <table style="margin-bottom: 0;">
                    <tr><th style="width: 30%; background-color: #fff8e1;">Proxy/VPN判定</th><td style="background-color: #ffffff;"><strong>{{ proxy_info | e }}</strong><br><small style="color: #555;">情報元: {{ proxy_source | e }}</small></td></tr>
                    <tr><th style="background-color: #fff8e1;">脅威判定(IoT/C2)</th><td style="background-color: #ffffff;"><strong>{{ iot_risk | e }}</strong><br><small style="color: #555;">情報元: {{ threat_source | e }}</small></td></tr>
                </table>
            </div>
        </div>

        <!-- 2. サブネット情報 -->
        {% if show_subnet %}
        <div id="tab-subnet" class="tab-content">
            {% if subnet.version == 4 %}
            <h1 class="theme-ipinfo" style="color: #00695c; border-color: #00695c;">サブネット・ネットワーク範囲計算 (IPv4)</h1>
            <div class="description" style="background-color: #e0f2f1; border-color: #b2dfdb;">
                <strong>論理ネットワーク範囲：</strong><br>
                RDAPの公式割当範囲（startAddress 〜 endAddress）に基づき、正確なネットワーク境界（CIDR）を算出した結果を示す。
            </div>
            <h2>IPアドレスクラス及び基本情報</h2>
            <table>
                <tr><th>対象IPアドレス</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>IPアドレスクラス</th><td><strong>{{ subnet.class | e }}</strong></td></tr>
                <tr><th>算出基準</th><td><strong>RDAP公式割当範囲</strong></td></tr>
            </table>
            <h2>ネットワーク範囲の計算結果</h2>
            <table>
                <tr><th>サブネットマスク</th><td><strong>/{{ subnet.prefix }} ({{ subnet.netmask }})</strong></td></tr>
                <tr><th>ネットワークアドレス<br>(開始IP)</th><td><strong>{{ subnet.network_addr }}</strong></td></tr>
                <tr><th>ホストアドレス範囲<br>(使用可能IP)</th><td><strong>{{ subnet.host_min }} ～ {{ subnet.host_max }}</strong></td></tr>
                <tr><th>ブロードキャストアドレス<br>(終了IP)</th><td><strong>{{ subnet.broadcast_addr }}</strong></td></tr>
                <tr><th>アドレス数</th><td><strong>IPアドレス総数: {{ subnet.total_ips }} (ホストアドレス数: {{ subnet.num_hosts }})</strong></td></tr>
            </table>
            {% else %}
            <h1 class="theme-ipinfo" style="color: #4a148c; border-color: #4a148c;">サブネット・ネットワーク範囲計算 (IPv6)</h1>
            <div class="description" style="background-color: #f3e5f5; border-color: #e1bee7;">
                <strong>IPv6 論理ネットワーク範囲：</strong><br>
                RDAPの公式割当範囲に基づき、正確なネットワーク境界（CIDR）を算出した結果を示す。
            </div>
            <h2>IPv6 アドレス属性</h2>
            <table>
                <tr><th>対象IPアドレス</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>算出基準</th><td><strong>RDAP公式割当範囲</strong></td></tr>
                <tr><th>ネットワーク規模推定</th><td><strong>{{ subnet.scope | e }}</strong></td></tr>
            </table>
            <h2>ネットワーク範囲の計算結果</h2>
            <table>
                <tr><th>プレフィックス長</th><td><strong>/{{ subnet.prefix }}</strong></td></tr>
                <tr><th>ネットワークアドレス<br>(開始IP)</th><td><strong>{{ subnet.network_addr }}</strong></td></tr>
                <tr><th>アドレス範囲<br>(割当可能範囲)</th><td><strong>{{ subnet.network_addr }} ～<br>{{ subnet.last_addr }}</strong></td></tr>
                <tr><th>アドレス総数</th><td><strong>{{ subnet.total_ips }} 個</strong></td></tr>
            </table>
            {% endif %}
        </div>
        {% endif %}

        <!-- 3. DNS正引き -->
        {% if show_nslookup %}
        <div id="tab-nslookup" class="tab-content">
            <h1 class="theme-rdap" style="color: #424242; border-color: #424242;">DNS正引き・MX解決結果 (dnspython)</h1>
            {% if ns.disposables %}
            <div style="background-color: #ffebee; border-left: 5px solid #f44336; padding: 15px; margin-bottom: 20px; border-radius: 4px;">
                <strong style="color: #c62828; font-size: 1.1em;">使い捨てメールサービス (Disposable Email) を検知</strong><br>
                <span style="color: #b71c1c; font-size: 0.9em;">対象のドメイン、またはそのMX（メール交換）レコードが、使い捨てメールサービスのインフラを示している。</span>
            </div>
            {% endif %}
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>DNS (Domain Name System) 正引き解決記録：</strong><br>
                入力されたドメイン名に対し、IPアドレス（A/AAAA/MXレコード）の特定を行った結果を示す。<br>
                一般的な <code>nslookup</code> コマンドは実行環境のDNS設定に依存するが、本ツールではPythonの専門ライブラリを使用して、信頼性の高いパブリックDNSへ<strong>直接的に問い合わせ</strong>を行っている。
            </div>
            <h2>対象ドメイン及び取得結果</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong>{{ domain_name | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                <tr><th>取得IPアドレス<br>(Resolved IPs)</th><td><strong>{{ ns.ips | safe }}</strong></td></tr>
                {% if ns.disposables %}
                <tr><th>使い捨てメール判定<br>(Disposable Service)</th><td><strong style="color: #c62828;">該当あり ({{ ns.disposables | join('、') | e }})</strong></td></tr>
                {% endif %}
            </table>
            <h2>内部実行クエリ (Python)</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold;">>>> {{ ns.cmd | e }}</div>
            <h2>実行結果 (ライブラリ出力)</h2>
            <div class="raw-data">{{ ns.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 4. ドメイン情報 (TLD) -->
        {% if show_tld %}
        <div id="tab-domain-info" class="tab-content">
            <h1 class="theme-rdap" style="color: #2e7d32; border-color: #2e7d32;">ドメイン統括情報 (TLD)</h1>
            <div class="description" style="background-color: #e8f5e9; border-color: #a5d6a7;">
                <strong>Domain Information：</strong><br>
                対象ドメインを管轄するトップレベルドメイン(TLD)情報を示す。
            </div>
            <h2>対象ドメイン</h2>
            <table><tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{{ domain_name | e }}</strong></td></tr></table>
            <h2>トップレベルドメイン (TLD) 管理情報</h2>
            <table>
                <tr><th>TLD</th><td><strong>.{{ tld.ext | e }}</strong></td></tr>
                <tr><th>管轄国 / 種別 (日本語)</th><td><strong>{{ tld.jp_name | e }}</strong> ({{ tld.name | e }})</td></tr>
                <tr><th>管理元 (レジストリ) URL</th><td>{% if tld.url %}<a href="{{ tld.url }}" target="_blank" style="color: #0066cc; font-weight: bold;">{{ tld.url }}</a>{% else %}情報なし{% endif %}</td></tr>
                <tr><th>IANA 公式データベース</th><td>{% if tld.iana %}<a href="{{ tld.iana }}" target="_blank" style="color: #0066cc; font-weight: bold;">{{ tld.iana }}</a>{% else %}情報なし{% endif %}</td></tr>
            </table>
        </div>
        {% endif %}

        <!-- 5. Domain RDAP -->
        {% if show_domain_rdap %}
        <div id="tab-domain-rdap" class="tab-content">
            <h1 class="theme-rdap" style="color: #2e7d32; border-color: #2e7d32;">RDAP取得結果（ドメイン属性）</h1>
            <div class="description" style="background-color: #e8f5e9; border-color: #a5d6a7;">
                <strong>Domain RDAP Information：</strong><br>
                公式レジストリから直接取得した法的登録情報（RDAP）を示す。
            </div>
            <h2>対象ドメイン及び回答元レジストリ情報等</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{{ domain_name | e }}</strong></td></tr>
                <tr><th>回答元レジストリ<br>(Registry)</th><td><strong>{{ d_rdap.registry | e }}</strong></td></tr>
                <tr><th>参照元URL<br>(Source)</th><td><a href="{{ d_rdap.url }}" target="_blank" style="color: #0066cc; word-break: break-all; font-weight: bold;">{{ d_rdap.url }}</a></td></tr>
            </table>
            <h2>RDAP取得結果</h2>
            <table>
                <tr><th>登録組織名<br>(Registrant Org)</th><td><strong>{{ d_rdap.registrant | e }}</strong></td></tr>
                <tr><th>管理レジストラ<br>(Registrar)</th><td><strong>{{ d_rdap.registrar | e }}</strong></td></tr>
                <tr><th>ネームサーバー<br>(Nameservers)</th><td><strong>{{ d_rdap.ns_html | safe }}</strong></td></tr>
                <tr><th>登録日時<br>(Registration Date)</th><td><strong>{{ d_rdap.reg_date | e }}</strong></td></tr>
                <tr><th>有効期限<br>(Expiration Date)</th><td><strong>{{ d_rdap.exp_date | e }}</strong></td></tr>
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{{ d_rdap.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 6. Domain WHOIS -->
        {% if show_domain_whois %}
        <div id="tab-domain-whois" class="tab-content">
            <h1 class="theme-rdap" style="color: #607d8b; border-color: #607d8b;">WHOIS取得結果（Port 43）</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>Domain WHOIS Information：</strong><br>
                Whoisプロトコル（ポート43経由）で権威サーバーから取得した生のWHOISテキストデータを示す。
            </div>
            <h2>対象ドメイン及び回答元サーバー</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{{ domain_name | e }}</strong></td></tr>
                <tr><th>回答元サーバー<br>(WHOIS Server)</th><td><strong>{{ d_whois.server | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
            </table>
            <h2>実行コマンド</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; margin-bottom: 20px;">$ whois -h {{ d_whois.server | e }} {{ domain_name | e }}</div>
            <h2>WHOISデータ</h2>
            <div class="raw-data" style="white-space: pre-wrap;">{{ d_whois.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 7. IP RDAP -->
        {% if show_ip_rdap %}
        <div id="tab-rdap" class="tab-content">
            <h1 class="theme-rdap" style="color: #1e3a8a; border-color: #1e3a8a;">RDAP取得結果（IPアドレス属性）</h1>
            <div class="description" style="background-color: #e3f2fd; border-color: #90caf9;">
                <strong>IP RDAP Information：</strong><br>
                インターネット資源（IPアドレス等）の登録主体（組織又は個人）を法的に特定し得る登録情報を取得した結果を示す。
            </div>
            <h2>対象IPアドレス及び回答元レジストリ情報等</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                <tr><th>回答元レジストリ<br>(Registry)</th><td><strong>{{ i_rdap.registry | e }}</strong></td></tr>
                <tr><th>参照元URL<br>(Source)</th><td><a href="{{ i_rdap.url }}" target="_blank" style="color: #0066cc; word-break: break-all; font-weight: bold;">{{ i_rdap.url }}</a></td></tr>
            </table>
            <h2>RDAP取得結果</h2>
            <table>
                <tr><th>法的保有者<br>(Key: name)</th><td><strong>{{ i_rdap.name | e }}</strong><span class="help-text">対象のIPアドレスブロックを公式に管理・保有している組織名（レジストリ登録情報）を示す。</span></td></tr>
                {% if i_rdap.remarks %}
                <tr><th>備考・プロジェクト情報<br>(Remarks / Description)</th><td><strong>{{ i_rdap.remarks | safe }}</strong><span class="help-text">RDAPデータの備考欄に記載されている付加情報であり、保有者と運用者が異なる理由等が記載されている場合がある。</span></td></tr>
                {% endif %}
                <tr><th>登録国コード<br>(Key: country)</th><td><strong>{{ i_rdap.country | e }}</strong><span class="help-text">当該IPアドレス資源が法的に割り当てられている管轄国を示す。</span></td></tr>
                <tr><th>IPアドレス割当範囲<br>(Key: startAddress, endAddress)</th><td><strong>{{ i_rdap.start | e }} ～ {{ i_rdap.end | e }}</strong><span class="help-text">対象のIPアドレスを包含する、レジストリから当該組織に対して運用および管理権限が委譲されたIPアドレス帯域を示す。</span></td></tr>
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{{ i_rdap.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 8. IP WHOIS -->
        {% if show_ip_whois %}
        <div id="tab-ip-whois" class="tab-content">
            <h1 class="theme-rdap" style="color: #607d8b; border-color: #607d8b;">WHOIS取得結果（Port 43）</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>IP WHOIS Information：</strong><br>
                WHOISプロトコル（ポート43経由）で取得したWHOISテキストデータを示す。
            </div>
            <h2>対象IPアドレス及び回答元サーバー</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>回答元サーバー<br>(WHOIS Server)</th><td><strong>{{ i_whois.server | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
            </table>
            <h2>実行コマンド</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; margin-bottom: 20px;">$ whois -h {{ i_whois.server | e }} {{ clean_ip | e }}</div>
            <h2>WHOISデータ</h2>
            <div class="raw-data" style="white-space: pre-wrap;">{{ i_whois.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 9. IPinfo -->
        {% if show_ipinfo %}
        <div id="tab-ipinfo" class="tab-content">
            <h1 class="theme-ipinfo">Whois属性及び地理位置情報取得結果</h1>
            <div class="description">
                <strong>IPinfo（IP Geolocation Data）：</strong><br>
                IPinfoとは、IPアドレスに基づき、当該アドレスの推定地理的位置（国、都市、地域、郵便番号、緯度経度等）、所属組織（ASN、ISP名、ドメイン等）、ネットワーク特性を判定するサービスである。
            </div>
            <h2>基本情報</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Key: ip)</th><td><strong>{{ ipinfo.ip | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                <tr><th>リクエストURL<br>(Request URL)</th><td><a href="{{ ipinfo.req_url }}" target="_blank" style="color: #00897b; word-break: break-all;">{{ ipinfo.req_url }}</a></td></tr>
            </table>
            <h2>IP情報取得結果</h2>
            <table>
                <tr><th>ホストネーム<br>(Key: hostname)</th><td><strong>{{ ipinfo.hostname | e }}</strong></td></tr>
                <tr><th>組織/ISP<br>(Key: org)</th><td><strong>{{ ipinfo.org | e }}</strong></td></tr>
            </table>
            <h2>地理的情報{% if ipinfo.privacy %}・匿名化判定{% endif %}</h2>
            <table>
                <tr><th>地域<br>(Key: city, region, country)</th><td><strong>{{ ipinfo.region | e }}</strong></td></tr>
                <tr><th>推定座標<br>(Key: loc)</th><td><strong>{{ ipinfo.loc | e }}</strong></td></tr>
                {% if ipinfo.privacy %}
                <tr><th>プライバシー・リスク判定<br>(Privacy Status)</th><td><strong>{{ ipinfo.privacy | e }}</strong><span class="help-text">VPN、Proxy、Tor、Hosting等として利用されているかを判定した結果。</span></td></tr>
                {% endif %}
            </table>
            {% if ipinfo.map_url %}
            <h2>位置情報マップ</h2>
            <div class="map-container" style="width: 100%; height: 400px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px; overflow: hidden;">
                <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{{ ipinfo.map_url }}"></iframe>
            </div>
            {% endif %}
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{{ ipinfo.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 10. VPNAPI -->
        {% if show_vpnapi %}
        <div id="tab-vpnapi" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #6a1b9a; border-color: #6a1b9a;">匿名通信・中継サーバー判定結果</h1>
            <div class="description" style="background-color: #f3e5f5; border-color: #ce93d8;">
                <strong>匿名通信総合判定：</strong><br>
                ローカルDBおよび外部API（VPNAPI.io）の評価を統合し、対象IPアドレスがVPN、プロキシ、Torノード、またはホスティングサーバーとして利用されているかを判定した結果を示す。
            </div>
            <h2>基本情報</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{{ vpnapi.req_ip | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                {% if vpnapi.has_api %}
                <tr><th>リクエストURL<br>(Request URL)</th><td><a href="https://vpnapi.io/api/{{ vpnapi.req_ip | e }}?key=********" target="_blank" style="color: #6a1b9a; word-break: break-all;">https://vpnapi.io/api/{{ vpnapi.req_ip | e }}?key=********</a></td></tr>
                {% endif %}
            </table>
            <h2>総合判定結果 (Attribution)</h2>
            <table>
                <tr><th style="width: 30%;">総合ステータス</th><td><strong style="color:{{ vpnapi.comp_color }}; font-size: 1.1em;">{{ vpnapi.comp_text | e }}</strong></td></tr>
                <tr><th>検知内容および情報元<br>(Source)</th><td><strong style="font-size: 1.1em;">{{ proxy_info | e }}</strong></td></tr>
            </table>
            <h2>VPNAPI.io 取得結果 (外部動的API詳細)</h2>
            {% if vpnapi.has_api %}
            <table>
                <tr><th>プロキシ判定<br>(Security)</th><td><strong style="color:{{ vpnapi.status_color }};">{{ vpnapi.status_text | e }}</strong></td></tr>
                <tr><th>検知種別<br>(Detected Types)</th><td><strong>{{ vpnapi.types | e }}</strong></td></tr>
                <tr><th>運用組織名<br>(Key: autonomous_system_organization)</th><td><strong>{{ vpnapi.org | e }}</strong></td></tr>
                <tr><th>判定国名<br>(Key: country)</th><td><strong>{{ vpnapi.country | e }}</strong></td></tr>
            </table>
            <h2>解析用生データ (JSON形式)</h2>
            <div class="raw-data">{{ vpnapi.raw | safe }}</div>
            {% else %}
            <p style="color: #666; font-size: 14px; padding: 10px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 4px;">※ VPNAPI.ioのAPIキーが未設定、または動的検証がスキップされたため、APIの詳細データはありません。</p>
            {% endif %}
        </div>
        {% endif %}

        <!-- 11. SecurityTrails History -->
        {% if show_st_history %}
        <div id="tab-st" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #e65100; border-color: #e65100;">レコード履歴 (SecurityTrails)</h1>
            <div class="description" style="background-color: #fff3e0; border-color: #ffcc80;">
                <strong>SecurityTrails Historical DNS Data：</strong><br>
                SecurityTrailsのAPIを利用して、対象ドメインに過去紐付いていたIPアドレス（Aレコード/AAAAレコード）の変遷を取得した結果を示す。
            </div>
            <h2>対象ドメイン及び取得情報</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong>{{ domain_name | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                {% if st.filtered %}
                <tr><th>抽出期間 (開始日)<br>(Start Date)</th><td><strong>{{ st.start | e }}</strong></td></tr>
                <tr><th>抽出期間 (終了日)<br>(End Date)</th><td><strong>{{ st.end | e }}</strong></td></tr>
                {% endif %}
                <tr><th>リクエストURL<br>(Request URL)</th><td>
                    <a href="https://api.securitytrails.com/v1/history/{{ domain_name | e }}/dns/a" target="_blank" style="color: #0066cc; word-break: break-all;">https://api.securitytrails.com/v1/history/{{ domain_name | e }}/dns/a</a><br>
                    <a href="https://api.securitytrails.com/v1/history/{{ domain_name | e }}/dns/aaaa" target="_blank" style="color: #0066cc; word-break: break-all;">https://api.securitytrails.com/v1/history/{{ domain_name | e }}/dns/aaaa</a>
                </td></tr>
            </table>
            <h2>判明したIPアドレス一覧 (重複排除)</h2>
            <table>
                <tr><th>抽出されたIPアドレス (IPv4/IPv6)</th></tr>
                {% if st.is_error %}
                <tr><td style="text-align:center;">-</td></tr>
                {% elif st.unique_ips %}
                    {% for u_ip in st.unique_ips %}<tr><td><strong>{{ u_ip | e }}</strong></td></tr>{% endfor %}
                {% else %}
                <tr><td style="text-align:center;">取得されたIPアドレスはありません。</td></tr>
                {% endif %}
            </table>
            <h2>レコード履歴 ({% if st.filtered %}抽出結果全件{% else %}最新20件{% endif %})</h2>
            <table>
                <tr><th>IPアドレス (IPv4/IPv6)</th><th>初回観測日 (First Seen)</th><th>最終観測日 (Last Seen)</th><th>組織 (Organization)</th></tr>
                {% if st.is_error %}
                <tr><td colspan='4' style='text-align:center; color:#c62828;'><b>🚨 月間の無料APIリクエスト枠（50回）に到達したため、履歴の取得がブロックされました。</b></td></tr>
                {% elif st.records %}
                    {% for rec in st.records %}
                    <tr>
                        <td>{% for v in rec.values %}{{ v.ip | e }}{% if not loop.last %}<br>{% endif %}{% endfor %}</td>
                        <td>{{ rec.first_seen | default('情報なし', true) | e }}</td>
                        <td>{{ rec.last_seen | default('情報なし', true) | e }}</td>
                        <td>{{ rec.organizations[0] | default('情報なし', true) | e if rec.organizations else '情報なし' }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                <tr><td colspan='4' style='text-align:center;'>A/AAAAレコードの履歴データが見つかりませんでした。</td></tr>
                {% endif %}
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{{ st.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 12. Reverse IP -->
        {% if show_st_revip %}
        <div id="tab-st-revip" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #0288d1; border-color: #0288d1;">Reverse IP 検索結果 (Passive DNS)</h1>
            <div class="description" style="background-color: #e1f5fe; border-color: #81d4fa;">
                <strong>Reverse IP Lookup：</strong><br>
                対象のIPアドレスがA/AAAAレコードとして設定されているドメイン群を、{{ revip.source | e }} のPassive DNSデータベースから逆引き検索した結果を示す。同一インフラに同居している他のサービス群の特定に利用する。
            </div>
            <h2>対象IPアドレス及び取得結果</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                <tr><th>情報元<br>(Data Source)</th><td><strong>{{ revip.source | e }}</strong></td></tr>
                <tr><th>ヒット総数<br>(Total Records)</th><td>
                    {% if revip.is_error %}エラー (上限到達)
                    {% elif revip.pages > 1 %}
                        {% if revip.records | length >= revip.total %}<strong>{{ revip.total }} 件</strong> (全件取得済)
                        {% else %}<strong>{{ revip.total }} 件</strong> (※最初の {{ revip.records | length }} 件のみ表示)
                        {% endif %}
                    {% else %}<strong>{{ revip.total }} 件</strong>
                    {% endif %}
                </td></tr>
            </table>
            <h2>紐づくドメイン一覧</h2>
            <table>
                <tr><th>ドメイン名 (Hostname)</th></tr>
                {% if revip.is_error %}
                <tr><td style='text-align:center; color:#c62828;'><b>🚨 月間の無料APIリクエスト枠（50回）に到達したため、取得がブロックされました。</b></td></tr>
                {% elif revip.is_partial %}
                <tr><td style='text-align:center; background-color:#fff3e0; color:#e65100;'><b>⚠️ 全件取得の途中でAPI上限に到達しました。取得できた {{ revip.records | length }} 件までを表示します。</b></td></tr>
                {% endif %}
                
                {% if revip.records %}
                    {% for host in revip.records %}<tr><td><strong>{{ host | e }}</strong></td></tr>{% endfor %}
                {% elif not revip.is_error %}
                <tr><td style='text-align:center;'>紐づくドメインは見つかりませんでした。</td></tr>
                {% endif %}
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{{ revip.raw | safe }}</div>
        </div>
        {% endif %}

        <!-- 13. rDNS -->
        {% if show_rdns %}
        <div id="tab-rdns" class="tab-content">
            <h1 class="theme-rdap" style="color: #424242; border-color: #424242;">DNS逆引き解決結果 (dnspython)</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>DNS逆引き(Reverse DNS) 解決記録：</strong><br>
                対象のIPアドレスに対してPython公式の国際標準ライブラリである <code>dnspython</code> を実行し、紐づくホスト名（PTRレコード）を取得した結果を示す。
            </div>
            <h2>対象IPアドレス及び取得結果</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{{ clean_ip | e }}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{{ current_time }}</strong></td></tr>
                <tr><th>取得ホスト名<br>(Resolved Hostnames)</th><td><strong>{{ rdns.hosts | safe }}</strong></td></tr>
            </table>
            <h2>内部実行クエリ (Python)</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold;">>>> resolver.resolve(dns.reversename.from_address('{{ clean_ip | e }}'), 'PTR')</div>
            <h2>実行結果 (ライブラリ出力)</h2>
            <div class="raw-data">{{ rdns.raw | safe }}</div>
        </div>
        {% endif %}

        <script>
            function openTab(evt, tabId) {
                let i, tabcontent, tablinks;
                tabcontent = document.getElementsByClassName("tab-content");
                for (i = 0; i < tabcontent.length; i++) {
                    tabcontent[i].style.display = "none";
                }
                tablinks = document.getElementsByClassName("tab-button");
                for (i = 0; i < tablinks.length; i++) {
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }
                document.getElementById(tabId).style.display = "block";
                if(evt) {
                    evt.currentTarget.className += " active";
                } else {
                    let btn = document.getElementById("btn-" + tabId);
                    if(btn) btn.className += " active";
                }
            }
            window.onbeforeprint = function() {
                let tabcontents = document.getElementsByClassName("tab-content");
                for (let j = 0; j < tabcontents.length; j++) { tabcontents[j].style.display = "block"; }
            };
            window.onafterprint = function() {
                let activeTabId = "";
                let tablinks = document.getElementsByClassName("tab-button");
                for (let k = 0; k < tablinks.length; k++) {
                    if (tablinks[k].className.indexOf("active") > -1) { activeTabId = tablinks[k].id.replace("btn-", ""); break; }
                }
                if (activeTabId) { openTab(null, activeTabId); }
            };
        </script>
    </body>
    </html>
    """
    template = Template(template_str)
    return template.render(**ctx)

def generate_combined_html_report(target_results, report_opts=None):
    """複数の個別レポートを1つのHTMLファイル（目次付き）に統合する関数"""
    combined_body = ""
    toc_links = []
    common_style = ""
    
    for i, res in enumerate(target_results):
        target_ip = res.get('Target_IP', 'N/A')
        clean_ip = get_copy_target(target_ip)
        html_content = generate_individual_html_report(res, clean_ip, report_opts)
        if not html_content: continue
        
        # 1つ目のHTMLから共通スタイルを抽出
        if not common_style:
            style_match = re.search(r'<style>(.*?)</style>', html_content, re.DOTALL)
            if style_match: common_style = style_match.group(1)
            
        body_match = re.search(r'<body>(.*?)</body>', html_content, re.DOTALL)
        if body_match:
            bc = body_match.group(1)
            uid = f"_{i}"
            
            # 個別レポート用のコントロールパネルを削除
            bc = re.sub(r'<div class="controls no-print">.*?</button>\s*</div>', '', bc, flags=re.DOTALL)
            
            # 2件目以降は、長文になる解説（description）と補足（help-text）をHTMLから完全に削除して圧縮
            if i > 0:
                bc = re.sub(r'<div class="description".*?</div>', '', bc, flags=re.DOTALL)
                bc = re.sub(r'<span class="help-text">.*?</span>', '', bc, flags=re.DOTALL)
            
            # タブIDとJS関数名の置換（複数IP間でタブ切り替えが干渉しないようにUIDを付与）
            bc = bc.replace('id="tab-', f'id="tab{uid}-')
            bc = bc.replace('id="btn-tab-', f'id="btn-tab{uid}-')
            bc = bc.replace("openTab(event, 'tab-", f"openTab{uid}(event, 'tab{uid}-")
            bc = bc.replace('function openTab(evt, tabId)', f'function openTab{uid}(evt, tabId)')
            bc = bc.replace('openTab(null, ', f'openTab{uid}(null, ')
            bc = re.sub(r"openTab\{uid\}\(null,\s*'tab-(.*?)'\);", rf"openTab{uid}(null, 'tab{uid}-\1');", bc)
            
            # DOM取得スコープの限定
            bc = bc.replace('document.getElementsByClassName("tab-content")', f'document.getElementById("report-wrapper{uid}").getElementsByClassName("tab-content")')
            bc = bc.replace('document.getElementsByClassName("tab-button")', f'document.getElementById("report-wrapper{uid}").getElementsByClassName("tab-button")')
            
            # 個別印刷イベントの削除
            bc = re.sub(r'window\.onbeforeprint\s*=\s*function\(\)\s*\{.*?\};', '', bc, flags=re.DOTALL)
            bc = re.sub(r'window\.onafterprint\s*=\s*function\(\)\s*\{.*?\};', '', bc, flags=re.DOTALL)
            
            toc_links.append(f"<li><a href='#target{uid}' style='text-decoration: none; color: #1e3a8a; font-weight: bold;'>{clean_ip}</a></li>")
            
            # 重複するH2見出しを削除し、目次からのアンカー用divのみを配置
            combined_body += f"""
            <div id='target{uid}' style='margin-bottom: 60px; padding-bottom: 20px; border-bottom: 3px dashed #ccc; page-break-inside: avoid;'>
                <div id='report-wrapper{uid}'>{bc}</div>
            </div>
            """

    if not combined_body: return None
    
    # 統合用の追加CSSと印刷制御JS
    common_style += """
        body { background-color: #f0f2f5; }
        .main-container { background-color: white; padding: 40px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); max-width: 900px; margin: 0 auto; }
        .toc { background-color: #e3f2fd; padding: 20px; border-radius: 5px; margin-bottom: 40px; border: 1px solid #bbdefb; }
        .toc h2 { margin-top: 0; color: #1565c0; font-size: 22px; border-bottom: 2px solid #1565c0; padding-bottom: 5px; }
        .toc ul { column-count: 2; list-style-type: none; padding-left: 0; }
        .toc li { margin-bottom: 8px; padding: 5px; background: white; border-radius: 3px; border: 1px solid #ddd; text-align: center; }
        .toc li:hover { background: #bbdefb; }
        .combined-controls { background: #e3f2fd; padding: 15px; border-radius: 5px; border: 1px solid #bbdefb; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .combined-controls label { font-size: 14px; cursor: pointer; font-weight: bold; color: #1565c0; margin-right: 15px; display: inline-block; }
        .combined-controls button { padding: 10px 20px; font-size: 14px; font-weight: bold; background-color: #1e3a8a; color: white; border: none; border-radius: 5px; cursor: pointer; transition: 0.3s; }
        .combined-controls button:hover { background-color: #1565c0; }
        @media print {
            body { background-color: white; }
            .main-container { box-shadow: none; padding: 0; max-width: 100%; }
            .toc { page-break-after: always; }
        }
    """
    
    combined_js = """
    <script>
        window.onbeforeprint = function() {
            let tabcontents = document.getElementsByClassName("tab-content");
            for (let j = 0; j < tabcontents.length; j++) { tabcontents[j].style.display = "block"; }
        };
    </script>
    """

    full_combined_html = f"""
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Combined IP-OSINT Report</title>
        <style>{common_style}</style>
    </head>
    <body>
        <div class="main-container">
            <h1 style="text-align: center; color: #333; font-size: 28px; margin-bottom: 30px;">🔎 統合 IP-OSINT 調査レポート</h1>
            
            <div class="combined-controls no-print">
                <div>
                    <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-desc', !this.checked)"> 解説・ヘルプテキストを表示</label>
                    <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-hl', !this.checked)"> JSONのハイライトを有効化</label>
                    <label><input type="checkbox" onchange="document.body.classList.toggle('compress-json', this.checked)"> 生データ(JSON)を圧縮表示</label>
                </div>
                <button onclick="window.print()">🖨️ この統合レポートを一括印刷する</button>
            </div>

            <div class="toc no-print">
                <h2>📑 目次 (Target List)</h2>
                <ul>{''.join(toc_links)}</ul>
            </div>
            {combined_body}
        </div>
        {combined_js}
    </body>
    </html>
    """
    return full_combined_html