# reports.py
from utils import is_valid_ip, extract_actual_ip, is_valid_domain, is_ipv4
import json
import html
import re
import datetime
from urllib.parse import urlparse
import uuid
import ipaddress
import tempfile
import os
import zipfile
import pandas as pd
import streamlit as st
import altair as alt


from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.chart import BarChart, Reference, Series
from openpyxl.chart.label import DataLabelList
from openpyxl.chart.axis import ChartLines
from openpyxl.chart.layout import Layout, ManualLayout
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

from constants import TLD_INFO, RIR_LINKS
from utils import is_valid_ip, extract_actual_ip

def get_copy_target(ip_display):
    if not ip_display: return ""
    return str(ip_display).split(' - ')[0].split(' ')[0]

# HTMLレポート生成関数
def generate_full_report_html(isp_full_df, country_full_df, freq_full_df):
    
    def create_chunked_chart_specs(df, x_col, y_col, title_base, chunk_size=50):
        specs = []
        # データ全体での最大値を取得 (ページまたぎのスケール統一のため)
        global_max = df[x_col].max() if not df.empty else 0

        # データフレームを分割
        chunks = [df[i:i + chunk_size] for i in range(0, df.shape[0], chunk_size)]
        
        for i, chunk in enumerate(chunks):
            chart_title = f"{title_base} ({i+1}/{len(chunks)})" if len(chunks) > 1 else title_base
            
            # 数値ラベル付きチャート
            # x軸のスケールを全体最大値で固定する
            base = alt.Chart(chunk).encode(
                x=alt.X(x_col, title='Count', scale=alt.Scale(domain=[0, global_max])),
                y=alt.Y(y_col, sort='-x', title=y_col),
                tooltip=[y_col, x_col]
            )
            bars = base.mark_bar()
            text = base.mark_text(
                align='left',
                baseline='middle',
                dx=5, 
                fontSize=11,
                fontWeight='bold'
            ).encode(
                text=x_col
            )
            chart = (bars + text).properties(
                title=chart_title,
                width=700,
                height=alt.Step(20) 
            )
            specs.append(chart.to_dict())
        return specs

    # 各カテゴリのチャートスペックを生成
    target_specs = create_chunked_chart_specs(freq_full_df, 'Count', 'Target_IP', 'Target IP Counts (All)')
    isp_specs = create_chunked_chart_specs(isp_full_df, 'Count', 'ISP', 'ISP Counts (All)')
    country_specs = create_chunked_chart_specs(country_full_df, 'Count', 'Country', 'Country Counts (All)')

    # HTMLテンプレート
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <title>Whois Search Full Report</title>
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body {{ font-family: "Helvetica Neue", Arial, sans-serif; padding: 40px; background-color: #fff; color: #333; }}
        h1 {{ text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }}
        h2 {{ 
            color: #1e3a8a; 
            margin-top: 50px; 
            border-left: 5px solid #1e3a8a; 
            padding-left: 15px; 
            page-break-before: always; 
        }}
        h2:first-of-type {{ page-break-before: auto; }} 
        
        .chart-container {{ 
            margin-bottom: 40px; 
            padding: 10px; 
            page-break-inside: avoid; 
        }}
        
        @media print {{
            body {{ padding: 0; background-color: #fff; }}
            .no-print {{ display: none; }}
            h2 {{ margin-top: 20px; }}
        }}
      </style>
    </head>
    <body>
      <h1>Whois検索結果分析レポート</h1>
      <p style="text-align: center; color: #666;">Generated by Whois Search Tool</p>

      <h2>対象IPアドレス カウント (全 {len(freq_full_df)} 件)</h2>
      <div id="target_charts"></div>

      <h2>ISP別 カウント (全 {len(isp_full_df)} 件)</h2>
      <div id="isp_charts"></div>

      <h2>国別 カウント (全 {len(country_full_df)} 件)</h2>
      <div id="country_charts"></div>

      <script type="text/javascript">
        // Embed charts function
        function embedCharts(containerId, specs) {{
            const container = document.getElementById(containerId);
            specs.forEach((spec, index) => {{
                const div = document.createElement('div');
                div.id = containerId + '_' + index;
                div.className = 'chart-container';
                container.appendChild(div);
                vegaEmbed('#' + div.id, spec, {{actions: false}});
            }});
        }}

        // Data from Python (Serialized to JSON)
        const targetSpecs = {json.dumps(target_specs)};
        const ispSpecs = {json.dumps(isp_specs)};
        const countrySpecs = {json.dumps(country_specs)};

        // Render
        if (targetSpecs.length > 0) embedCharts('target_charts', targetSpecs);
        else document.getElementById('target_charts').innerHTML = '<p>データなし</p>';

        if (ispSpecs.length > 0) embedCharts('isp_charts', ispSpecs);
        else document.getElementById('isp_charts').innerHTML = '<p>データなし</p>';

        if (countrySpecs.length > 0) embedCharts('country_charts', countrySpecs);
        else document.getElementById('country_charts').innerHTML = '<p>データなし</p>';
      </script>
    </body>
    </html>
    """
    return html_template

# --- 🛡️ 脅威インテリジェンス (STIX 2.1) 生成関数 ---
def generate_stix2_bundle(results):
    """ 調査結果をSTIX 2.1形式のBundle (JSON) に変換する """
    objects = []
    # STIXの時刻は UTC の ISO8601 形式が必須
    now_utc = datetime.datetime.now(datetime.timezone.utc)
    now_str = now_utc.strftime('%Y-%m-%dT%H:%M:%S.000Z')

    # 1. ツール自身のIdentity（作成者）オブジェクト
    identity_id = f"identity--{uuid.uuid4()}"
    objects.append({
        "type": "identity",
        "spec_version": "2.1",
        "id": identity_id,
        "created": now_str,
        "modified": now_str,
        "name": "検索大臣 - IP/Domain OSINT Tool",
        "identity_class": "system"
    })

    # 2. 各ターゲットをIndicator（脅威インジケーター）オブジェクトとして変換
    for res in results:
        target = res.get("Target_IP", "")
        if not target or target == "N/A": continue
        
        # 集約モード時の表記 (1.1.1.1 - 1.1.1.5) やドメイン複合 (example.com (1.1.1.1)) をクリーンアップ
        clean_target = str(target).split(' - ')[0].split(' ')[0]
        if "(" in clean_target:
            clean_target = clean_target.split("(")[0].strip()

        # STIXのサイバー観測パターンの構築
        try:
            ip_obj = ipaddress.ip_address(clean_target)
            if ip_obj.version == 4:
                pattern = f"[ipv4-addr:value = '{clean_target}']"
            else:
                pattern = f"[ipv6-addr:value = '{clean_target}']"
        except ValueError:
            pattern = f"[domain-name:value = '{clean_target}']"

        isp = res.get("ISP_JP", "N/A")
        country = res.get("Country_JP", "N/A")
        proxy = res.get("Proxy_Type", "")
        risk = res.get("IoT_Risk", "")

        # 脅威の説明文を構築
        desc = f"【OSINT調査結果】\nISP: {isp}\n国: {country}\n匿名化/クラウド: {proxy if proxy else 'なし'}\nIoTリスク: {risk}"
        
        # SOC向けのアラート用ラベル
        labels = ["osint-target"]
        if proxy and proxy != "未検証" and "Standard" not in proxy: 
            labels.append("anonymization-proxy-vpn")
        if risk and risk not in ["[No Match]", "[Not Checked]", ""]: 
            labels.append("vulnerable-iot")

        indicator_id = f"indicator--{uuid.uuid4()}"
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": indicator_id,
            "created_by_ref": identity_id,
            "created": now_str,
            "modified": now_str,
            "name": f"OSINT Target: {clean_target}",
            "description": desc,
            "indicator_types": ["malicious-activity" if len(labels) > 1 else "anomalous-activity"],
            "pattern": pattern,
            "pattern_type": "stix",
            "valid_from": now_str,
            "labels": labels
        })

    # 3. すべてを1つのBundleにパッキング
    bundle = {
        "type": "bundle",
        "id": f"bundle--{uuid.uuid4()}",
        "objects": objects
    }
    
    return json.dumps(bundle, indent=4, ensure_ascii=False)

# 📈 クロス分析用HTMLレポート生成関数
def generate_cross_analysis_html(chart_spec, x_col, group_col):
    html_template = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <title>Whois Cross Analysis Report</title>
      <script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-lite@5"></script>
      <script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
      <style>
        body {{ font-family: "Helvetica Neue", Arial, sans-serif; padding: 40px; background-color: #fff; color: #333; }}
        h1 {{ text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 30px; }}
        .info {{ text-align: center; color: #666; margin-bottom: 20px; }}
        .chart-container {{ 
            width: 100%; 
            display: flex; 
            justify-content: center; 
            margin-bottom: 40px; 
            padding: 10px; 
        }}
      </style>
    </head>
    <body>
      <h1>クロス分析レポート: {x_col} vs {group_col}</h1>
      <p class="info">Generated by Whois Search Tool</p>

      <div id="chart" class="chart-container"></div>

      <script type="text/javascript">
        const spec = {json.dumps(chart_spec)};
        vegaEmbed('#chart', spec, {{actions: true}});
      </script>
    </body>
    </html>
    """
    return html_template

# --- Excel生成ヘルパー関数 ---
def convert_df_to_excel(df):
    with tempfile.NamedTemporaryFile(delete=False, suffix=".xlsx") as tmp:
        tmp_excel_path = tmp.name
    try:
        with pd.ExcelWriter(tmp_excel_path, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Sheet1')
        with open(tmp_excel_path, "rb") as f:
            data = f.read()
        return data
    finally:
        if os.path.exists(tmp_excel_path):
            os.remove(tmp_excel_path)

# --- Advanced Excel Generator (Pivot & Chart) ---
def create_advanced_excel(df, time_col_name=None):
    with tempfile.NamedTemporaryFile(delete=False, suffix=".xlsx") as tmp:
        tmp_excel_path = tmp.name
    
    try:
        # 1. IPアドレスが含まれているかを判定 (すべての列を検査してIP列を正確に特定する)
        target_col = 'IPアドレス' if 'IPアドレス' in df.columns else ('Target_IP' if 'Target_IP' in df.columns else df.columns[0])
        has_ip = False
        for col in df.columns:
            # 最初の数行をチェックしてIPアドレスを含む列を探す
            if any(is_valid_ip(str(val)) for val in df[col].dropna().head(20)):
                has_ip = True
                target_col = col
                break
        
        # ==========================================
        # パターンA: すべてドメイン(非IP)の場合
        # ==========================================
        if not has_ip:
            if target_col in df.columns:
                df = df.rename(columns={target_col: 'Target Domain'})
            # 不要な列を削除（統一した列名に対応）
            cols_to_drop = ['Whois(元データ)', 'Whois(日本語名)', '国名（英語）', '国名', 'プロキシ種別', 'ステータス', 'IoTリスク', 'RDAP(元データ)', 'RDAP(日本語名)', 'ISP', 'ISP_JP', 'Country', 'Country_JP']
            df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors='ignore')
            with pd.ExcelWriter(tmp_excel_path, engine='openpyxl') as writer:
                df.to_excel(writer, index=False, sheet_name='Domain Results')
            with open(tmp_excel_path, "rb") as f:
                data = f.read()
            return data

        # ==========================================
        # パターンB: IPアドレスが含まれる場合 (分析グラフ付き)
        # ==========================================
        # 必須カラムの補完 (統一した列名を基準にする)
        required_cols = {
            'プロキシ種別': '',
            'Whois(日本語名)': 'N/A',
            '国名': 'N/A'
        }
        for col, default_val in required_cols.items():
            if col not in df.columns:
                df[col] = default_val

        # データ前処理：空欄や欠損値を空文字（何もなし）に統一
        df['プロキシ種別'] = df['プロキシ種別'].fillna('')
        
        # --- プロキシ種別の表記簡略化 (Excel出力専用) ---
        def clean_proxy_text(text):
            if not text or pd.isna(text): return "未検証"
            t = str(text)
            # "(Source: ...)" などの情報源表記を削除
            t = re.sub(r'\s*\((Source:|API Verified|Local DB)[^)]*\)', '', t)
            # "API Confirmed (VPN)" -> "VPN" のように抽出
            t = re.sub(r'API Confirmed \((.*?)\)', r'\1', t)
            # "[VPN/PROXY]" -> "VPN/PROXY" のようにブラケットを外す
            t = re.sub(r'\[(.*?)\]', r'\1', t)
            t = t.strip(' /')
            return t if t else "未検証"
            
        if 'プロキシ種別' in df.columns:
            df['プロキシ種別'] = df['プロキシ種別'].apply(clean_proxy_text)
        
        has_time_analysis = False
        if time_col_name and time_col_name in df.columns:
            try:
                df['Hour'] = pd.to_datetime(df[time_col_name], errors='coerce').dt.hour
                has_time_analysis = True
            except Exception:
                pass

        count_col = df.columns[0]

        # 書き込み開始
        with pd.ExcelWriter(tmp_excel_path, engine='openpyxl') as writer:
            df.to_excel(writer, index=False, sheet_name='Raw Data')
            wb = writer.book
            
            def add_chart_sheet(pivot_df, sheet_name, chart_title, x_title, y_title, description, chart_type="col", stacked=False):
                if pivot_df.empty: return
                pivot_df.to_excel(writer, sheet_name=sheet_name, startrow=4)
                ws = wb[sheet_name]
                ws['A1'] = chart_title
                ws['A1'].font = Font(size=14, bold=True, color="1E3A8A")
                ws['A2'] = description
                ws['A2'].font = Font(size=11, color="555555", italic=True)
                ws['A2'].alignment = Alignment(wrap_text=True, vertical="top")
                ws.merge_cells('A2:H3')
                
                chart = BarChart()
                chart.type = chart_type
                chart.style = 10 
                chart.title = chart_title
                chart.height = 15 
                chart.width = 25  
                # 凡例を非表示にする
                chart.legend = None
                
                if stacked:
                    chart.grouping = "stacked"
                    chart.overlap = 100
                else:
                    chart.varyColors = True
                    
                chart.dataLabels = DataLabelList()
                chart.dataLabels.showVal = True
                    
                chart.x_axis.title = x_title
                chart.y_axis.title = y_title
                chart.y_axis.majorGridlines = ChartLines() 
                chart.y_axis.delete = False        
                chart.y_axis.numFmt = '0'          
                chart.y_axis.majorTickMark = 'out' 
                chart.y_axis.tickLblPos = 'nextTo' 
                chart.layout = Layout(manualLayout=ManualLayout(x=0.03, y=0.05, h=0.75, w=0.85))
                
                data_start_row = 5 
                data_end_row = data_start_row + len(pivot_df)
                data = Reference(ws, min_col=2, min_row=data_start_row, max_row=data_end_row, max_col=len(pivot_df.columns)+1)
                cats = Reference(ws, min_col=1, min_row=data_start_row+1, max_row=data_end_row)
                chart.add_data(data, titles_from_data=True)
                chart.set_categories(cats)
                ws.add_chart(chart, "E5")

            # プロキシデータが有効か（全て空文字ではないか）を判定するフラグ
            proxy_col = 'プロキシ種別'
            has_valid_risk_data = False
            if proxy_col in df.columns:
                if not (df[proxy_col] == '').all():
                    has_valid_risk_data = True

            # 1. Report_Whois_Volume: ISP別アクセス数
            isp_col = 'Whois(日本語名)'
            if isp_col in df.columns and not (df[isp_col] == 'N/A').all():
                top_isps = df[isp_col].value_counts().head(20).index
                df_isp = df[df[isp_col].isin(top_isps)]
                pivot_isp_vol = df_isp.pivot_table(index=isp_col, values=count_col, aggfunc='count')
                
                if not pivot_isp_vol.empty:
                    pivot_isp_vol = pivot_isp_vol.sort_values(count_col, ascending=False)
                    desc_isp_vol = "どの組織・プロバイダからのアクセスが最も多いかを可視化しています。特定のISPからのアクセス集中は、そのサービスの利用者層または特定のキャンペーンの影響を示唆します。"
                    add_chart_sheet(pivot_isp_vol, 'Report_Whois_Volume', 'Whois Access Volume Ranking (Top 20)', 'ISP Name', 'Count', desc_isp_vol)

                # 2. Report_Whois_Risk: ISP別リスク分析
                if has_valid_risk_data:
                    pivot_isp_risk = df_isp.pivot_table(index=isp_col, columns=proxy_col, values=count_col, aggfunc='count', fill_value=0)
                    if not pivot_isp_risk.empty:
                        desc_isp_risk = "そのISPが安全な一般回線か、注意が必要なサーバー/VPN経由かを判定しています。「未検証」はAPIによる検証なし、「Standard Connection (API Verified)」はAPI検証済みの一般回線を示します。"
                        add_chart_sheet(pivot_isp_risk, 'Report_Whois_Risk', 'Risk Analysis by Whois (Top 20)', 'ISP Name', 'Count', desc_isp_risk, stacked=True)

            # 3. Report_RDAP_Volume: RDAP別アクセス数
            rdap_col = 'RDAP(日本語名)'
            if rdap_col in df.columns:
                df[rdap_col] = df[rdap_col].replace('', 'N/A')
                
                if not (df[rdap_col] == 'N/A').all():
                    top_rdaps = df[rdap_col].value_counts().head(20).index
                    df_rdap = df[df[rdap_col].isin(top_rdaps)]
                    pivot_rdap_vol = df_rdap.pivot_table(index=rdap_col, values=count_col, aggfunc='count')
                    
                    if not pivot_rdap_vol.empty:
                        pivot_rdap_vol = pivot_rdap_vol.sort_values(count_col, ascending=False)
                        desc_rdap_vol = "公式レジストリ（RDAP）に登録されている法的な保有組織ごとのアクセス数です。Whois（運用者）とは異なる、IPアドレスブロックの真の所有者傾向を可視化します。"
                        add_chart_sheet(pivot_rdap_vol, 'Report_RDAP_Volume', 'RDAP Access Volume Ranking (Top 20)', 'RDAP Name', 'Count', desc_rdap_vol)

                    # 4. Report_RDAP_Risk: RDAP別リスク分析
                    if has_valid_risk_data:
                        pivot_rdap_risk = df_rdap.pivot_table(index=rdap_col, columns=proxy_col, values=count_col, aggfunc='count', fill_value=0)
                        if not pivot_rdap_risk.empty:
                            desc_rdap_risk = "法的保有組織（RDAP）ごとの接続環境を分析しています。特定の組織が保有するIP帯域が、プロキシやVPNインフラとして集中的に悪用されていないかを確認できます。"
                            add_chart_sheet(pivot_rdap_risk, 'Report_RDAP_Risk', 'Risk Analysis by RDAP (Top 20)', 'RDAP Name', 'Count', desc_rdap_risk, stacked=True)
            
            # 5. Report_Country: 国別アクセス数
            if '国名' in df.columns and not (df['国名'] == 'N/A').all():
                pivot_country = df.pivot_table(index='国名', values=count_col, aggfunc='count')
                if not pivot_country.empty:
                    pivot_country = pivot_country.sort_values(count_col, ascending=False).head(15)
                    desc_country = "国ごとのアクセス数をランキング化しています。サービス提供エリア外からの予期せぬアクセス検知や、海外からの攻撃予兆の発見に役立ちます。"
                    add_chart_sheet(pivot_country, 'Report_Country', 'Country Access Volume (Top 15)', 'Country Name', 'Count', desc_country)

            # 6. Report_Time: 時間帯分析
            if has_time_analysis:
                pivot_time_vol = df.pivot_table(index='Hour', values=count_col, aggfunc='count', fill_value=0).reindex(range(24), fill_value=0)
                desc_time_vol = "何時にアクセスが集中しているかを可視化しています。一般的なユーザーは活動時間帯に、Botなどは深夜早朝や24時間一定のアクセスを行う傾向があります。"
                add_chart_sheet(pivot_time_vol, 'Report_Time_Volume', 'Hourly Access Trend', 'Hour (0-23h)', 'Count', desc_time_vol)

                if has_valid_risk_data:
                    pivot_time_risk = df.pivot_table(index='Hour', columns=proxy_col, values=count_col, aggfunc='count', fill_value=0).reindex(range(24), fill_value=0)
                    desc_time_risk = "深夜帯などに怪しいアクセス（Hosting/VPN等）が増えていないかを確認できます。夜間にHosting判定が増加する場合、Botによる自動巡回の可能性があります。"
                    add_chart_sheet(pivot_time_risk, 'Report_Time_Risk', 'Hourly Risk Trend', 'Hour (0-23h)', 'Count', desc_time_risk, stacked=True)
                
        with open(tmp_excel_path, "rb") as f:
            data = f.read()
        return data
    finally:
        if os.path.exists(tmp_excel_path):
            os.remove(tmp_excel_path)

def generate_individual_html_report(res, clean_ip, report_opts=None, resolved_dns_map=None):
    """
    個別IPの詳細HTMLレポートを生成する
    
    Args:
        res: 検索結果辞書
        clean_ip: 表示用IPアドレス
        report_opts: レポート出力オプション辞書
        resolved_dns_map: DNS解決結果辞書（st.session_stateから渡す）
    """
    if resolved_dns_map is None:
        resolved_dns_map = {}
    if report_opts is None:
        report_opts = {"tld": True, "dns": True, "subnet": True, "rdap": True, "whois": True, "ipinfo": True, "vpnapi": True, "st": True, "rdns": True, "revip": True}
    
    # --- データの展開 ---
    target_ip = res.get('Target_IP', 'N/A')
    rdap_url = res.get('RDAP_URL')
    rdap_json = res.get('RDAP_JSON')
    ipinfo_json = res.get('IPINFO_JSON')
    vpnapi_json = res.get('VPNAPI_JSON')
    domain_rdap_json = res.get('DOMAIN_RDAP_JSON')
    domain_rdap_url = res.get('DOMAIN_RDAP_URL')
    domain_whois_text = res.get('DOMAIN_WHOIS_TEXT')
    domain_whois_server = res.get('DOMAIN_WHOIS_SERVER')
    ip_whois_text = res.get('IP_WHOIS_TEXT') 
    ip_whois_server = res.get('IP_WHOIS_SERVER')  
    st_json = res.get('ST_JSON')
    st_rev_json = res.get('ST_REVERSE_IP_JSON', None) 
    
    # 判定ソースの解析（ProxyとIoTリスクから抽出）
    proxy_info = res.get('Proxy_Type', 'Standard Connection')
    iot_risk = res.get('IoT_Risk', '[Not Checked]')
    
    # ソース抽出用ロジック（カッコ内の文字列をソースとして扱う）
    proxy_source = re.search(r'\((Source:.*?)\)', proxy_info)
    proxy_source_str = proxy_source.group(1) if proxy_source else "Dynamic/API"
    
    threat_source = re.search(r'\((Source:.*?)\)', iot_risk)
    threat_source_str = threat_source.group(1) if threat_source else "External Intelligence"
    
    rdns_data = res.get('RDNS_DATA', {})
    rdns_raw = rdns_data.get('raw', '') if isinstance(rdns_data, dict) else ""
    rdns_hosts = rdns_data.get('hosts', []) if isinstance(rdns_data, dict) else []
    
    nslookup_data = {}
    domain_name_for_nslookup = ""
    
    if "(" in target_ip and ")" in target_ip:
        domain_name_for_nslookup = target_ip.split("(")[0].strip()
        nslookup_data = resolved_dns_map.get(domain_name_for_nslookup, {})
    elif not is_valid_ip(target_ip): 
        domain_name_for_nslookup = target_ip
        nslookup_data = resolved_dns_map.get(domain_name_for_nslookup, {})
    
    nslookup_raw = nslookup_data.get('raw', '') if isinstance(nslookup_data, dict) else ""
    nslookup_ips = nslookup_data.get('ips', []) if isinstance(nslookup_data, dict) else []
    
    if isinstance(nslookup_data, str):
        nslookup_raw = nslookup_data
    
    # --- ローカルDBでの検知フラグ ---
    has_proxy_alert = proxy_info and proxy_info not in ["Standard Connection", "N/A (Domain)", "N/A", "未検証"]

    # 外部APIのデータ、またはローカルDBでのプロキシ検知のいずれかがあればレポートを生成する
    if not ((rdap_url and rdap_json) or ipinfo_json or domain_rdap_json or domain_whois_text or nslookup_raw or st_json or rdns_raw or ip_whois_text or st_rev_json or has_proxy_alert):
        return None # レポート生成に必要なデータがない場合は None を返す

    jst_timezone = datetime.timezone(datetime.timedelta(hours=9))
    now_jst = datetime.datetime.now(jst_timezone)
    current_time_str = now_jst.strftime("%Y年%m月%d日 %H時%M分")

    # --- 判定根拠セクションの独立構築 ---
    attribution_section = f"""
    <div class="attribution-box" style="background-color: #fff3e0; padding: 15px; border-radius: 5px; border: 1px solid #ffe0b2; margin-bottom: 20px;">
        <h2 style="margin-top: 0; color: #d84315; border-left: 4px solid #d84315; padding-left: 10px; font-size: 18px;">📊 判定根拠 (Attribution)</h2>
        <table style="margin-bottom: 0;">
            <tr><th style="width: 30%; background-color: #fff8e1;">Proxy/VPN判定</th><td style="background-color: #ffffff;"><strong>{html.escape(proxy_info)}</strong><br><small style="color: #555;">情報源: {proxy_source_str}</small></td></tr>
            <tr><th style="background-color: #fff8e1;">脅威判定(IoT/C2)</th><td style="background-color: #ffffff;"><strong>{html.escape(iot_risk)}</strong><br><small style="color: #555;">情報源: {threat_source_str}</small></td></tr>
        </table>
    </div>
    """

    # 判定根拠を「最初のタブ」として新設
    tab_id_overview = "tab-overview"
    first_tab_id = tab_id_overview
    tabs_html = f'<button class="tab-button" onclick="openTab(event, \'{tab_id_overview}\')" id="btn-{tab_id_overview}">概要・判定根拠</button>\n'
    
    contents_html = f"""
    <div id="{tab_id_overview}" class="tab-content">
        <h1 style="color: #d84315; border-bottom: 2px solid #d84315;">調査対象: {clean_ip}</h1>
        <div class="description" style="background-color: #fff9c4; border-color: #fbc02d;">
            このタブでは、対象に対する各種検知ロジックの総合判定結果（サマリー）を表示しています。
        </div>
        {attribution_section}
    </div>
    """
    
    # --- 2. サブネット・ネットワーク情報 (IPv4 / IPv6 両対応) ---
    try:
        ip_obj = ipaddress.ip_address(clean_ip)
        # RDAPから正確な開始・終了IPが取得できているか判定
        has_rdap_range = bool(rdap_json and "startAddress" in rdap_json and "endAddress" in rdap_json)
        
        # サブネット情報はRDAPで正確な範囲が特定できた場合のみ構築する (RDAPオプションがONのとき限定)
        if report_opts.get("rdap", False) and has_rdap_range:
            tab_id = "tab-subnet"
            if not first_tab_id: first_tab_id = tab_id
            tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">サブネット情報</button>\n'
            # ==========================================
            # IPv4 の場合の処理
            # ==========================================
            if ip_obj.version == 4:
                target_net = None
                calc_source = "RDAP公式割当範囲"
                
                try:
                    s_ip = ipaddress.IPv4Address(rdap_json["startAddress"])
                    e_ip = ipaddress.IPv4Address(rdap_json["endAddress"])
                    cidrs = list(ipaddress.summarize_address_range(s_ip, e_ip))
                    for cidr in cidrs:
                        if ip_obj in cidr:
                            target_net = cidr
                            break
                except Exception:
                    pass
                
                if target_net:
                    first_octet = int(str(ip_obj).split('.')[0])
                    if 1 <= first_octet <= 126: ip_class = "クラスA"
                    elif 128 <= first_octet <= 191: ip_class = "クラスB"
                    elif 192 <= first_octet <= 223: ip_class = "クラスC"
                    elif 224 <= first_octet <= 239: ip_class = "クラスD マルチキャスト"
                    elif 240 <= first_octet <= 255: ip_class = "クラスE 実験用"
                    else: ip_class = "不明"
    
                    host_min = str(target_net[1]) if target_net.num_addresses > 2 else "なし"
                    host_max = str(target_net[-2]) if target_net.num_addresses > 2 else "なし"
                    num_hosts = max(0, target_net.num_addresses - 2)
    
                    subnet_content = f"""
                    <div id="{tab_id}" class="tab-content">
                        <h1 class="theme-ipinfo" style="color: #00695c; border-color: #00695c;">サブネット・ネットワーク範囲計算 (IPv4)</h1>
                        <div class="description" style="background-color: #e0f2f1; border-color: #b2dfdb;">
                            <strong>論理ネットワーク範囲：</strong><br>
                            RDAPの公式割当範囲（startAddress 〜 endAddress）に基づき、正確なネットワーク境界（CIDR）を算出した結果を示す。
                        </div>
                        <h2>IPアドレスクラス及び基本情報</h2>
                        <table>
                            <tr><th>対象IPアドレス</th><td><strong>{clean_ip}</strong></td></tr>
                            <tr><th>IPアドレスクラス</th><td><strong>{ip_class}</strong></td></tr>
                            <tr><th>算出基準</th><td><strong>{calc_source}</strong></td></tr>
                        </table>
                        <h2>ネットワーク範囲の計算結果</h2>
                        <table>
                            <tr><th>サブネットマスク</th><td><strong>/{target_net.prefixlen} ({target_net.netmask})</strong></td></tr>
                            <tr><th>ネットワークアドレス<br>(開始IP)</th><td><strong>{target_net.network_address}</strong></td></tr>
                            <tr><th>ホストアドレス範囲<br>(使用可能IP)</th><td><strong>{host_min} ～ {host_max}</strong></td></tr>
                            <tr><th>ブロードキャストアドレス<br>(終了IP)</th><td><strong>{target_net.broadcast_address}</strong></td></tr>
                            <tr><th>アドレス数</th><td><strong>IPアドレス総数: {target_net.num_addresses} (ホストアドレス数: {num_hosts})</strong></td></tr>
                        </table>
                    </div>
                    """
                    contents_html += subnet_content

            # ==========================================
            # IPv6 の場合の処理
            # ==========================================
            elif ip_obj.version == 6:
                target_net = None
                calc_source = "RDAP公式割当範囲"
                
                try:
                    s_ip = ipaddress.IPv6Address(rdap_json["startAddress"])
                    e_ip = ipaddress.IPv6Address(rdap_json["endAddress"])
                    cidrs = list(ipaddress.summarize_address_range(s_ip, e_ip))
                    for cidr in cidrs:
                        if ip_obj in cidr:
                            target_net = cidr
                            break
                except Exception:
                    pass

                if target_net:
                    prefix = target_net.prefixlen
                    if prefix <= 32:
                        scope_desc = "LIR / 大規模ISP割当 (非常に広大なインフラ空間)"
                    elif prefix <= 48:
                        scope_desc = "企業・大規模拠点割当 (一般的なエンタープライズ境界)"
                    elif prefix <= 56:
                        scope_desc = "一般家庭・小規模拠点割当 (コンシューマ向けルーター等)"
                    elif prefix == 64:
                        scope_desc = "単一セグメント (標準的な1つのLAN・VLAN)"
                    else:
                        scope_desc = "デバイス・ホスト固有割当"
    
                    total_ips = target_net.num_addresses
                    if total_ips > 1000000:
                        ips_display = f"2^{128 - prefix} 個 (約 {total_ips:.2e})"
                    else:
                        ips_display = f"{total_ips} 個"
    
                    network_addr = str(target_net.network_address)
                    last_addr = str(target_net.broadcast_address) 
    
                    subnet_content = f"""
                    <div id="{tab_id}" class="tab-content">
                        <h1 class="theme-ipinfo" style="color: #4a148c; border-color: #4a148c;">サブネット・ネットワーク範囲計算 (IPv6)</h1>
                        <div class="description" style="background-color: #f3e5f5; border-color: #e1bee7;">
                            <strong>IPv6 論理ネットワーク範囲：</strong><br>
                            RDAPの公式割当範囲（startAddress 〜 endAddress）に基づき、正確なネットワーク境界（CIDR）を算出した結果を示す。
                        </div>
                        <h2>IPv6 アドレス属性</h2>
                        <table>
                            <tr><th>対象IPアドレス</th><td><strong>{clean_ip}</strong></td></tr>
                            <tr><th>算出基準</th><td><strong>{calc_source}</strong></td></tr>
                            <tr><th>ネットワーク規模推定</th><td><strong>{scope_desc}</strong></td></tr>
                        </table>
                        <h2>ネットワーク範囲の計算結果</h2>
                        <table>
                            <tr><th>プレフィックス長</th><td><strong>/{prefix}</strong></td></tr>
                            <tr><th>ネットワークアドレス<br>(開始IP)</th><td><strong>{network_addr}</strong></td></tr>
                            <tr><th>アドレス範囲<br>(割当可能範囲)</th><td><strong>{network_addr} ～<br>{last_addr}</strong></td></tr>
                            <tr><th>アドレス総数</th><td><strong>{ips_display}</strong></td></tr>
                        </table>
                    </div>
                    """
                    contents_html += subnet_content
    except ValueError:
        pass

    # --- 3. nslookup (DNS正引き) ---
    if nslookup_raw and report_opts.get("dns", True):
        tab_id = "tab-nslookup"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">DNS正引き</button>\n'
        
        escaped_nslookup = html.escape(nslookup_raw)
        for ip_str in nslookup_ips:
            escaped_ip = html.escape(ip_str)
            escaped_nslookup = escaped_nslookup.replace(escaped_ip, f'<span class="json-hl">{escaped_ip}</span>')
            
        cmd_str = f"resolver = dns.resolver.Resolver(); resolver.nameservers=['8.8.8.8']; resolver.resolve('{domain_name_for_nslookup}', 'A/AAAA/MX')"
        ip_list_str = "<br>".join([html.escape(ip) for ip in nslookup_ips]) if nslookup_ips else "取得なし"
        
        detected_services = res.get('DISPOSABLE_SERVICES', [])
        
        table_alert_row = ""
        mx_alert_html = ""
        if detected_services:
            services_str = html.escape("、".join(detected_services))
            mx_alert_html = f"""
            <div style="background-color: #ffebee; border-left: 5px solid #f44336; padding: 15px; margin-bottom: 20px; border-radius: 4px;">
                <strong style="color: #c62828; font-size: 1.1em;">使い捨てメールサービス (Disposable Email) を検知</strong><br>
                <span style="color: #b71c1c; font-size: 0.9em;">対象のドメイン、またはそのMX（メール交換）レコードが、使い捨てメールサービスのインフラを示している。</span>
            </div>
            """
            table_alert_row = f"""
                <tr><th>使い捨てメール判定<br>(Disposable Service)</th><td><strong style="color: #c62828;">該当あり ({services_str})</strong></td></tr>
            """

        nslookup_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #424242; border-color: #424242;">DNS正引き・MX解決結果 (dnspython)</h1>
            {mx_alert_html}
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>DNS (Domain Name System) 正引き解決記録：</strong><br>
                入力されたドメイン名に対し、IPアドレス（A/AAAA/MXレコード）の特定を行った結果を示す。<br>
                一般的な <code>nslookup</code> コマンドは実行環境のDNS設定に依存するが、本ツールではPythonの専門ライブラリを使用して、信頼性の高いパブリックDNS（Google/Cloudflare）へ<strong>直接的に問い合わせ</strong>を行っている。<br>
            </div>
            <h2>対象ドメイン及び取得結果</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong>{html.escape(domain_name_for_nslookup)}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                <tr><th>取得IPアドレス<br>(Resolved IPs)</th><td><strong>{ip_list_str}</strong></td></tr>
                {table_alert_row}
            </table>
            <h2>内部実行クエリ (Python)</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; font-family: Consolas, monospace;">>>> {cmd_str}</div>
            <h2>実行結果 (ライブラリ出力)</h2>
            <div class="raw-data" style="font-family: Consolas, monospace;">{escaped_nslookup}</div>
        </div>
        """
        contents_html += nslookup_content

    # --- 4. ドメイン情報 (TLD) ---
    if domain_name_for_nslookup and report_opts.get("tld", True):
        tab_id = "tab-domain-info"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">ドメイン情報</button>\n'
        
        tld_val = domain_name_for_nslookup.split('.')[-1].lower() if '.' in domain_name_for_nslookup else ""
        tld_data = TLD_INFO.get(tld_val, {"name": "その他の国・地域 / gTLD", "jp_name": "未分類", "url": "N/A"})
        iana_url = f"https://www.iana.org/domains/root/db/{tld_val}.html" if tld_val else ""
        
        tld_url_html = f'<a href="{tld_data["url"]}" target="_blank" style="color: #0066cc; font-weight: bold;">{tld_data["url"]}</a>' if tld_data["url"] != "N/A" else "情報なし"
        iana_url_html = f'<a href="{iana_url}" target="_blank" style="color: #0066cc; font-weight: bold;">{iana_url}</a>' if iana_url else "情報なし"
        
        domain_info_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #2e7d32; border-color: #2e7d32;">ドメイン統括情報 (TLD)</h1>
            <div class="description" style="background-color: #e8f5e9; border-color: #a5d6a7;">
                <strong>Domain Information：</strong><br>
                対象ドメインを管轄するトップレベルドメイン(TLD)情報を示す。
            </div>
            <h2>対象ドメイン</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{html.escape(domain_name_for_nslookup)}</strong></td></tr>
            </table>
            <h2>トップレベルドメイン (TLD) 管理情報</h2>
            <table>
                <tr><th>TLD</th><td><strong>.{html.escape(tld_val)}</strong></td></tr>
                <tr><th>管轄国 / 種別 (日本語)</th><td><strong>{html.escape(tld_data['jp_name'])}</strong> ({html.escape(tld_data['name'])})</td></tr>
                <tr><th>管理元 (レジストリ) URL</th><td>{tld_url_html}</td></tr>
                <tr><th>IANA 公式データベース</th><td>{iana_url_html}</td></tr>
            </table>
        </div>
        """
        contents_html += domain_info_content

    # --- 4.1 RDAP (Domain) ---
    if domain_rdap_json and domain_rdap_url and report_opts.get("rdap", True):
        tab_id = "tab-domain-rdap"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">RDAP(Domain)</button>\n'
        
        parsed_url_d = urlparse(domain_rdap_url)
        registry_name_d = parsed_url_d.netloc if parsed_url_d.netloc else "不明"

        events = domain_rdap_json.get("events", [])
        reg_date = "情報なし"
        exp_date = "情報なし"
        for ev in events:
            if ev.get("eventAction") == "registration":
                reg_date = ev.get("eventDate", "情報なし")
            elif ev.get("eventAction") == "expiration":
                exp_date = ev.get("eventDate", "情報なし")

        entities = domain_rdap_json.get("entities", [])
        registrar_name = "情報なし"
        registrant_org = "情報なし"
        for ent in entities:
            roles = ent.get("roles", [])
            vcard_array = ent.get("vcardArray", [])
            if len(vcard_array) > 1:
                for vcard in vcard_array[1]:
                    if "registrar" in roles and vcard[0] == "fn":
                        registrar_name = vcard[3]
                    if "registrant" in roles and vcard[0] in ["org", "fn"]:
                        registrant_org = vcard[3]

        nameservers_data = domain_rdap_json.get("nameservers", [])
        ns_list = [ns.get("ldhName") for ns in nameservers_data if ns.get("ldhName")]
        ns_html = "<br>".join(ns_list) if ns_list else "情報なし"
        
        raw_json_str_d = json.dumps(domain_rdap_json, indent=4, ensure_ascii=False)
        escaped_json_d = html.escape(raw_json_str_d)
        
        highlight_keys_d = ['registrar', 'registrant', 'registration', 'expiration', 'nameservers']
        for hk in highlight_keys_d:
            escaped_json_d = escaped_json_d.replace(f'&quot;{hk}&quot;', f'<span class="json-hl">&quot;{hk}&quot;</span>')
        
        for val in [registrar_name, registrant_org, reg_date, exp_date]:
            if val and val != "情報なし":
                esc_val = html.escape(val)
                escaped_json_d = escaped_json_d.replace(f'&quot;{esc_val}&quot;', f'<span class="json-hl">&quot;{esc_val}&quot;</span>')

        domain_rdap_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #2e7d32; border-color: #2e7d32;">RDAP取得結果（ドメイン属性）</h1>
            <div class="description" style="background-color: #e8f5e9; border-color: #a5d6a7;">
                <strong>Domain RDAP Information：</strong><br>
                公式レジストリから直接取得した法的登録情報（RDAP）を示す。
            </div>
            <h2>対象ドメイン及び回答元レジストリ情報等</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{html.escape(domain_name_for_nslookup)}</strong></td></tr>
                <tr><th>回答元レジストリ<br>(Registry)</th><td><strong>{registry_name_d}</strong></td></tr>
                <tr><th>参照元URL<br>(Source)</th><td><a href="{domain_rdap_url}" target="_blank" style="color: #0066cc; word-break: break-all; font-weight: bold;">{domain_rdap_url}</a></td></tr>
            </table>
            <h2>RDAP取得結果</h2>
            <table>
                <tr><th>登録組織名<br>(Registrant Org)</th><td><strong>{registrant_org}</strong></td></tr>
                <tr><th>管理レジストラ<br>(Registrar)</th><td><strong>{registrar_name}</strong></td></tr>
                <tr><th>ネームサーバー<br>(Nameservers)</th><td><strong>{ns_html}</strong></td></tr>
                <tr><th>登録日時<br>(Registration Date)</th><td><strong>{reg_date}</strong></td></tr>
                <tr><th>有効期限<br>(Expiration Date)</th><td><strong>{exp_date}</strong></td></tr>
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json_d}</div>
        </div>
        """
        contents_html += domain_rdap_content

    # --- 4.2 WHOIS (Domain) ---
    if domain_whois_text and report_opts.get("whois", True):
        tab_id = "tab-domain-whois"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">WHOIS(Domain)</button>\n'
        
        escaped_whois = html.escape(str(domain_whois_text))
        escaped_server = html.escape(str(domain_whois_server))
        escaped_domain = html.escape(domain_name_for_nslookup)
        
        equiv_cmd = f"$ whois -h {escaped_server} {escaped_domain}"
        
        domain_whois_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #607d8b; border-color: #607d8b;">WHOIS取得結果（Port 43）</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>Domain WHOIS Information：</strong><br>
                Whoisプロトコル（ポート43経由）で権威サーバーから取得した生のWHOISテキストデータを示す。
            </div>
            <h2>対象ドメイン及び回答元サーバー</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong style="font-size: 1.2em;">{escaped_domain}</strong></td></tr>
                <tr><th>回答元サーバー<br>(WHOIS Server)</th><td><strong>{escaped_server}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
            </table>
            <h2>実行コマンド</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; font-family: Consolas, monospace; margin-bottom: 20px;">{equiv_cmd}</div>
            <h2>WHOISデータ</h2>
            <div class="raw-data" style="font-family: Consolas, monospace; white-space: pre-wrap;">{escaped_whois}</div>
        </div>
        """
        contents_html += domain_whois_content

    # --- 5. RDAP (IP) ---
    if rdap_json and rdap_url and report_opts.get("rdap", True):
        tab_id = "tab-rdap"
        if not first_tab_id: first_tab_id = tab_id
        
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">RDAP(IP)</button>\n'
        
        actual_rdap_url = rdap_url
        for link in rdap_json.get("links", []):
            if link.get("rel") == "self":
                actual_rdap_url = link.get("href", actual_rdap_url)
                break
        
        name_val = rdap_json.get("name", "情報なし")
        country_val = rdap_json.get("country", "情報なし")
        start_ip = rdap_json.get("startAddress", "情報なし")
        end_ip = rdap_json.get("endAddress", "情報なし")
        
        remarks_list = rdap_json.get("remarks", [])
        descriptions = []
        for remark in remarks_list:
            desc = remark.get("description", [])
            if isinstance(desc, list):
                descriptions.extend(desc)
            elif isinstance(desc, str):
                descriptions.append(desc)
        
        remarks_html = ""
        if descriptions:
            remarks_text = "<br>".join(descriptions)
            remarks_html = f"""
                <tr>
                    <th>備考・プロジェクト情報<br>(Remarks / Description)</th>
                    <td><strong>{remarks_text}</strong><span class="help-text">RDAPデータの備考欄に記載されている付加情報であり、保有者と運用者が異なる理由等が記載されている場合がある。</span></td>
                </tr>
            """

        country_display = country_val
        if country_val == "JP": country_display = "JP (Japan)"
        elif country_val == "US": country_display = "US (United States)"
        
        parsed_url = urlparse(actual_rdap_url)
        registry_name = parsed_url.netloc if parsed_url.netloc else "RDAP"

        raw_json_str = json.dumps(rdap_json, indent=4, ensure_ascii=False)
        escaped_json = html.escape(raw_json_str)
        
        highlight_keys = ['name', 'country', 'startAddress', 'endAddress']
        for hk in highlight_keys:
            simple_pattern = r'(&quot;' + hk + r'&quot;:\s*&quot;.*?&quot;)'
            escaped_json = re.sub(simple_pattern, r'<span class="json-hl">\1</span>', escaped_json)
        
        if descriptions:
            escaped_json = re.sub(r'(&quot;(remarks|description)&quot;\s*:)', r'<span class="json-hl">\1</span>', escaped_json)
            for desc in descriptions:
                esc_desc = html.escape(desc)
                target_str = f'&quot;{esc_desc}&quot;'
                replacement = f'<span class="json-hl">{target_str}</span>'
                escaped_json = escaped_json.replace(target_str, replacement)

        rdap_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #1e3a8a; border-color: #1e3a8a;">RDAP取得結果（IPアドレス属性）</h1>
            <div class="description" style="background-color: #e3f2fd; border-color: #90caf9;">
                <strong>IP RDAP Information：</strong><br>
                インターネット資源（IPアドレス等）の登録主体（組織又は個人）を法的に特定し得る登録情報を取得した結果を示す。
            </div>
            <h2>対象IPアドレス及び回答元レジストリ情報等</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{clean_ip}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                <tr><th>回答元レジストリ<br>(Registry)</th><td><strong>{registry_name}</strong></td></tr>
                <tr><th>参照元URL<br>(Source)</th><td><a href="{actual_rdap_url}" target="_blank" style="color: #0066cc; word-break: break-all; font-weight: bold;">{actual_rdap_url}</a></td></tr>
            </table>
            <h2>RDAP取得結果</h2>
            <table>
                <tr><th>法的保有者<br>(Key: name)</th><td><strong>{name_val}</strong><span class="help-text">対象のIPアドレスブロックを公式に管理・保有している組織名（レジストリ登録情報）を示す。</span></td></tr>
                {remarks_html}
                <tr><th>登録国コード<br>(Key: country)</th><td><strong>{country_display}</strong><span class="help-text">当該IPアドレス資源が法的に割り当てられている管轄国を示す。</span></td></tr>
                <tr><th>IPアドレス割当範囲<br>(Key: startAddress, endAddress)</th><td><strong>{start_ip} ～ {end_ip}</strong><span class="help-text">対象のIPアドレスを包含する、レジストリから当該組織に対して運用および管理権限が委譲されたIPアドレス帯域を示す。</span></td></tr>
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json}</div>
        </div>
        """
        contents_html += rdap_content

    # --- 5.1 WHOIS (IP) ---
    if ip_whois_text and report_opts.get("whois", True):
        tab_id = "tab-ip-whois"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">WHOIS(IP)</button>\n'
        
        escaped_whois = html.escape(str(ip_whois_text))
        escaped_server = html.escape(str(ip_whois_server))
        escaped_ip = html.escape(clean_ip)
        
        equiv_cmd = f"$ whois -h {escaped_server} {escaped_ip}"
        
        ip_whois_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #607d8b; border-color: #607d8b;">WHOIS取得結果（Port 43）</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>IP WHOIS Information：</strong><br>
                WHOISプロトコル（ポート43経由）で取得したWHOISテキストデータを示す。
            </div>
            <h2>対象IPアドレス及び回答元サーバー</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{escaped_ip}</strong></td></tr>
                <tr><th>回答元サーバー<br>(WHOIS Server)</th><td><strong>{escaped_server}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
            </table>
            <h2>実行コマンド</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; font-family: Consolas, monospace; margin-bottom: 20px;">{equiv_cmd}</div>
            <h2>WHOISデータ</h2>
            <div class="raw-data" style="font-family: Consolas, monospace; white-space: pre-wrap;">{escaped_whois}</div>
        </div>
        """
        contents_html += ip_whois_content

    # --- 6. IPinfo ---
    if ipinfo_json and report_opts.get("ipinfo", True):
        tab_id = "tab-ipinfo"
        if not first_tab_id: first_tab_id = tab_id
        
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">IPinfo</button>\n'
        
        raw_json_str = json.dumps(ipinfo_json, indent=4, ensure_ascii=False)
        escaped_json = html.escape(raw_json_str)
        
        highlight_keys = ['ip', 'hostname', 'city', 'region', 'country', 'loc', 'org']
        for hk in highlight_keys:
            simple_pattern = r'(&quot;' + hk + r'&quot;:\s*&quot;.*?&quot;)'
            escaped_json = re.sub(simple_pattern, r'<span class="json-hl">\1</span>', escaped_json)

        ip_val = ipinfo_json.get("ip", "情報なし")
        hostname_val = ipinfo_json.get("hostname", "情報なし")
        city_val = ipinfo_json.get("city", "情報なし")
        region_val = ipinfo_json.get("region", "情報なし")
        country_val = ipinfo_json.get("country", "情報なし")
        loc_val = ipinfo_json.get("loc", "情報なし")
        org_val = ipinfo_json.get("org", "情報なし")
        
        req_ipinfo_url = f"https://ipinfo.io/{ip_val if ip_val != '情報なし' else clean_ip}"

        privacy_html = ""
        geo_heading = "<h2>地理的情報</h2>"

        if "privacy" in ipinfo_json:
            privacy = ipinfo_json.get("privacy", {})
            privacy_flags = []
            if privacy.get("vpn"): privacy_flags.append("VPN")
            if privacy.get("proxy"): privacy_flags.append("Proxy")
            if privacy.get("tor"): privacy_flags.append("Tor")
            if privacy.get("relay"): privacy_flags.append("Relay")
            if privacy.get("hosting"): privacy_flags.append("Hosting")
            
            if privacy_flags:
                geo_heading = "<h2>地理的情報・匿名化判定</h2>"
                privacy_val = ", ".join(privacy_flags)
                privacy_html = f"""
                    <tr>
                        <th>プライバシー・リスク判定<br>(Privacy Status)</th>
                        <td><strong>{privacy_val}</strong><span class="help-text">VPN、Proxy、Tor、Hosting等として利用されているかを判定した結果。</span></td>
                    </tr>
                """

        map_html = ""
        if loc_val != "情報なし" and "," in loc_val:
            map_url = f"https://maps.google.com/maps?q={loc_val}&hl=ja&z=14&output=embed"
            map_html = f"""
            <h2>位置情報マップ</h2>
            <div class="map-container" style="width: 100%; height: 400px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px; overflow: hidden;">
                <iframe width="100%" height="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{map_url}"></iframe>
            </div>
            """

        ipinfo_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-ipinfo">Whois属性及び地理位置情報取得結果</h1>
            <div class="description">
                <strong>IPinfo（IP Geolocation Data）：</strong><br>
                IPinfoとは、IPアドレスに基づき、当該アドレスの推定地理的位置（国、都市、地域、郵便番号、緯度経度等）、所属組織（ASN、ISP名、ドメイン等）、ネットワーク特性を判定するサービスである。
            </div>
            <h2>基本情報</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Key: ip)</th><td><strong>{ip_val}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                <tr><th>リクエストURL<br>(Request URL)</th><td><a href="{req_ipinfo_url}" target="_blank" style="color: #00897b; word-break: break-all;">{req_ipinfo_url}</a></td></tr>
            </table>
            <h2>IP情報取得結果</h2>
            <table>
                <tr><th>ホストネーム<br>(Key: hostname)</th><td><strong>{hostname_val}</strong></td></tr>
                <tr><th>組織/ISP<br>(Key: org)</th><td><strong>{org_val}</strong></td></tr>
            </table>
            {geo_heading}
            <table>
                <tr><th>地域<br>(Key: city, region, country)</th><td><strong>{country_val}, {region_val}, {city_val}</strong></td></tr>
                <tr><th>推定座標<br>(Key: loc)</th><td><strong>{loc_val}</strong></td></tr>
                {privacy_html}
            </table>
            {map_html}
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json}</div>
        </div>
        """
        contents_html += ipinfo_content

    # --- 7. 匿名通信判定 (統合版: Local DB & VPNAPI.io) ---
    has_proxy_alert = proxy_info and proxy_info not in ["Standard Connection", "N/A (Domain)", "N/A"]
    if (vpnapi_json or has_proxy_alert) and report_opts.get("vpnapi", True):
        tab_id = "tab-vpnapi"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">匿名通信判定</button>\n'
        
        if vpnapi_json:
            sec = vpnapi_json.get('security') or {}
            if any(sec.values()):
                proxy_status_text = "該当あり (匿名通信検知)"
                status_color = "red"
                detected_types = [k.upper() for k, v in sec.items() if v]
                p_type_val = " / ".join(detected_types)
            else:
                proxy_status_text = "該当なし"
                status_color = "green"
                p_type_val = "情報なし"

            net = vpnapi_json.get('network') or {}
            org_val = net.get('autonomous_system_organization', '情報なし')

            loc = vpnapi_json.get('location') or {}
            c_name_val = loc.get('country', '情報なし')

            raw_json_str = json.dumps(vpnapi_json, indent=4, ensure_ascii=False)
            escaped_json = html.escape(raw_json_str)

            highlight_keys_vpn = ['vpn', 'proxy', 'tor', 'relay', 'country', 'ip', 'autonomous_system_organization']
            for hk in highlight_keys_vpn:
                simple_pattern = r'("' + hk + r'":\s*.*?,?\n)'
                escaped_json = re.sub(simple_pattern, r'<span class="json-hl">\1</span>', escaped_json)

            vpn_req_ip = vpnapi_json.get('ip', clean_ip)
            req_vpnapi_url = f"https://vpnapi.io/api/{vpn_req_ip}?key=********"
            
            vpnapi_detail_html = f"""
            <h2>VPNAPI.io 取得結果 (外部動的API詳細)</h2>
            <table>
                <tr><th>プロキシ判定<br>(Security)</th><td><strong style="color:{status_color};">{proxy_status_text}</strong></td></tr>
                <tr><th>検知種別<br>(Detected Types)</th><td><strong>{p_type_val}</strong></td></tr>
                <tr><th>運用組織名<br>(Key: autonomous_system_organization)</th><td><strong>{org_val}</strong></td></tr>
                <tr><th>判定国名<br>(Key: country)</th><td><strong>{c_name_val}</strong></td></tr>
            </table>
            <h2>解析用生データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json}</div>
            """
            url_html = f'<tr><th>リクエストURL<br>(Request URL)</th><td><a href="{req_vpnapi_url}" target="_blank" style="color: #6a1b9a; word-break: break-all;">{req_vpnapi_url}</a></td></tr>'
        else:
            vpn_req_ip = clean_ip
            url_html = ""
            vpnapi_detail_html = """
            <h2>VPNAPI.io 取得結果 (外部動的API詳細)</h2>
            <p style="color: #666; font-size: 14px; padding: 10px; background-color: #f9f9f9; border: 1px solid #ddd; border-radius: 4px;">※ VPNAPI.ioのAPIキーが未設定、または動的検証がスキップされたため、APIの詳細データはありません。</p>
            """

        if has_proxy_alert:
            comp_status_color = "#c62828"
            comp_status_text = "検知あり (不審・匿名化インフラ等)"
        else:
            comp_status_color = "#2e7d32"
            comp_status_text = "検知なし (Standard Connection)"

        vpnapi_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #6a1b9a; border-color: #6a1b9a;">匿名通信・中継サーバー判定結果</h1>
            <div class="description" style="background-color: #f3e5f5; border-color: #ce93d8;">
                <strong>匿名通信総合判定：</strong><br>
                ローカルDB（IP2Location LITE / FireHOL / Tor公式リスト等）および外部API（VPNAPI.io）の評価を統合し、対象IPアドレスがVPN、プロキシ、Torノード、またはホスティングサーバーとして利用されているかを判定した結果を示す。
            </div>
            <h2>基本情報</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{vpn_req_ip}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                {url_html}
            </table>
            <h2>総合判定結果 (Attribution)</h2>
            <table>
                <tr><th style="width: 30%;">総合ステータス</th><td><strong style="color:{comp_status_color}; font-size: 1.1em;">{comp_status_text}</strong></td></tr>
                <tr><th>検知内容および情報源<br>(Source)</th><td><strong style="font-size: 1.1em;">{html.escape(proxy_info)}</strong></td></tr>
            </table>
            {vpnapi_detail_html if report_opts.get("vpnapi", False) else ""}
        </div>
        """
        contents_html += vpnapi_content

    # --- 8. SecurityTrails ---
    if st_json and report_opts.get("st", True):
        tab_id = "tab-st"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">SecurityTrails</button>\n'
        
        records = st_json.get("records", [])
        is_date_filtered = st_json.get("is_date_filtered", False)
        st_start_date_str = st_json.get("start_date", "")
        st_end_date_str = st_json.get("end_date", "")
        
        st_html_rows = ""
        unique_ips_ordered = []
        seen_ips = set()

        if st_json.get("error") == "rate_limit":
            st_html_rows = "<tr><td colspan='4' style='text-align:center; color:#c62828;'><b>🚨 月間の無料APIリクエスト枠（50回）に到達したため、履歴の取得がブロックされました。</b></td></tr>"
            unique_ips_rows = "<tr><td style='text-align:center;'>-</td></tr>"
        else:
            for rec in records: 
                values = rec.get("values", [])
                ips_in_rec = []
                for v in values:
                    ip_val = v.get("ip", "")
                    if ip_val:
                        ips_in_rec.append(html.escape(str(ip_val)))
                        if ip_val not in seen_ips:
                            seen_ips.add(ip_val)
                            unique_ips_ordered.append(ip_val)

                ips = "<br>".join(ips_in_rec)
                first_seen = html.escape(str(rec.get("first_seen", "情報なし")))
                last_seen = html.escape(str(rec.get("last_seen", "情報なし")))
                orgs = rec.get("organizations", [])
                org = html.escape(str(orgs[0])) if orgs and orgs[0] else "情報なし"
                st_html_rows += f"<tr><td>{ips}</td><td>{first_seen}</td><td>{last_seen}</td><td>{org}</td></tr>"
                
            if not st_html_rows:
                st_html_rows = "<tr><td colspan='4' style='text-align:center;'>A/AAAAレコードの履歴データが見つかりませんでした。</td></tr>"
                
            unique_ips_rows = ""
            for ip in unique_ips_ordered:
                unique_ips_rows += f"<tr><td><strong>{html.escape(str(ip))}</strong></td></tr>"
            if not unique_ips_rows:
                unique_ips_rows = "<tr><td style='text-align:center;'>取得されたIPアドレスはありません。</td></tr>"

        raw_json_str_st = json.dumps(st_json, indent=4, ensure_ascii=False)
        escaped_json_st = html.escape(raw_json_str_st)
        
        highlight_keys_st = ['ip']
        for hk in highlight_keys_st:
            simple_pattern = r'((?:&quot;|")' + hk + r'(?:&quot;|")\s*:\s*[^\n\r]*)'
            escaped_json_st = re.sub(simple_pattern, r'<span class="json-hl">\1</span>', escaped_json_st)
            
        table_heading = "レコード履歴 (抽出結果全件)" if is_date_filtered else "レコード履歴 (最新20件)"
        target_domain_esc = html.escape(str(domain_name_for_nslookup))
        url_a = f"https://api.securitytrails.com/v1/history/{target_domain_esc}/dns/a"
        url_aaaa = f"https://api.securitytrails.com/v1/history/{target_domain_esc}/dns/aaaa"
        
        date_filter_html = ""
        if is_date_filtered and st_start_date_str and st_end_date_str:
            date_filter_html = f"""
                <tr><th>抽出期間 (開始日)<br>(Start Date)</th><td><strong>{html.escape(str(st_start_date_str))}</strong></td></tr>
                <tr><th>抽出期間 (終了日)<br>(End Date)</th><td><strong>{html.escape(str(st_end_date_str))}</strong></td></tr>
            """
        
        st_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #e65100; border-color: #e65100;">レコード履歴 (SecurityTrails)</h1>
            <div class="description" style="background-color: #fff3e0; border-color: #ffcc80;">
                <strong>SecurityTrails Historical DNS Data：</strong><br>
                SecurityTrailsのAPIを利用して、対象ドメインに過去紐付いていたIPアドレス（Aレコード/AAAAレコード）の変遷を取得した結果を示す。
            </div>
            <h2>対象ドメイン及び取得情報</h2>
            <table>
                <tr><th>対象ドメイン<br>(Target Domain)</th><td><strong>{target_domain_esc}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                {date_filter_html}
                <tr><th>リクエストURL<br>(Request URL)</th><td>
                    <a href="{url_a}" target="_blank" style="color: #0066cc; word-break: break-all;">{url_a}</a><br>
                    <a href="{url_aaaa}" target="_blank" style="color: #0066cc; word-break: break-all;">{url_aaaa}</a>
                </td></tr>
            </table>
            <h2>判明したIPアドレス一覧 (重複排除)</h2>
            <table>
                <tr><th>抽出されたIPアドレス (IPv4/IPv6)</th></tr>
                {unique_ips_rows}
            </table>
            <h2>{table_heading}</h2>
            <table>
                <tr><th>IPアドレス (IPv4/IPv6)</th><th>初回観測日 (First Seen)</th><th>最終観測日 (Last Seen)</th><th>組織 (Organization)</th></tr>
                {st_html_rows}
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json_st}</div>
        </div>
        """
        contents_html += st_content

    # --- 8.5 SecurityTrails / OTX (Reverse IP) ---
    if st_rev_json and report_opts.get("revip", True):
        tab_id = "tab-st-revip"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">Reverse IP</button>\n'
        
        records = st_rev_json.get("records", [])
        total_records = st_rev_json.get("meta", {}).get("total_records", len(records))
        total_pages = st_rev_json.get("meta", {}).get("total_pages", 1)
        
        if total_pages > 1:
            if len(records) >= total_records:
                display_count_text = f"<strong>{total_records} 件</strong> (全件取得済)"
            else:
                display_count_text = f"<strong>{total_records} 件</strong> (※最初の {len(records)} 件のみ表示)"
        else:
            display_count_text = f"<strong>{total_records} 件</strong>"
            
        rev_html_rows = ""
        
        if st_rev_json.get("error") == "rate_limit":
            rev_html_rows = "<tr><td style='text-align:center; color:#c62828;'><b>🚨 月間の無料APIリクエスト枠（50回）に到達したため、取得がブロックされました。</b></td></tr>"
            display_count_text = "エラー (上限到達)"
        elif st_rev_json.get("error") == "rate_limit_during_pagination":
            rev_html_rows = f"<tr><td style='text-align:center; background-color:#fff3e0; color:#e65100;'><b>⚠️ 全件取得の途中でAPI上限に到達しました。取得できた {len(records)} 件までを表示します。</b></td></tr>"
            for rec in records:
                hostname = rec.get("hostname", "")
                if hostname:
                    rev_html_rows += f"<tr><td><strong>{html.escape(str(hostname))}</strong></td></tr>"
        else:
            for rec in records:
                hostname = rec.get("hostname", "")
                if hostname:
                    rev_html_rows += f"<tr><td><strong>{html.escape(str(hostname))}</strong></td></tr>"
                    
            if not rev_html_rows:
                rev_html_rows = "<tr><td style='text-align:center;'>紐づくドメインは見つかりませんでした。</td></tr>"
            
        raw_json_str_rev = json.dumps(st_rev_json, indent=4, ensure_ascii=False)
        escaped_json_rev = html.escape(raw_json_str_rev)
        
        simple_pattern_rev = r'((?:&quot;|")hostname(?:&quot;|"):\s*(?:&quot;|").*?(?:&quot;|"))'
        escaped_json_rev = re.sub(simple_pattern_rev, r'<span class="json-hl">\1</span>', escaped_json_rev)
        
        source_name = st_rev_json.get("source", "SecurityTrails") if isinstance(st_rev_json, dict) else "SecurityTrails"

        rev_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-ip2proxy" style="color: #0288d1; border-color: #0288d1;">Reverse IP 検索結果 (Passive DNS)</h1>
            <div class="description" style="background-color: #e1f5fe; border-color: #81d4fa;">
                <strong>Reverse IP Lookup：</strong><br>
                対象のIPアドレスがA/AAAAレコードとして設定されているドメイン群を、{source_name} のPassive DNSデータベースから逆引き検索した結果を示す。同一インフラに同居している他のサービス群の特定に利用する。
            </div>
            <h2>対象IPアドレス及び取得結果</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{clean_ip}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                <tr><th>情報源<br>(Data Source)</th><td><strong>{source_name}</strong></td></tr>
                <tr><th>ヒット総数<br>(Total Records)</th><td>{display_count_text}</td></tr>
            </table>
            <h2>紐づくドメイン一覧</h2>
            <table>
                <tr><th>ドメイン名 (Hostname)</th></tr>
                {rev_html_rows}
            </table>
            <h2>参照元データ (JSON形式)</h2>
            <div class="raw-data">{escaped_json_rev}</div>
        </div>
        """
        contents_html += rev_content

    # --- 9. rDNS ---
    if rdns_raw and report_opts.get("rdns", True):
        tab_id = "tab-rdns"
        if not first_tab_id: first_tab_id = tab_id
        tabs_html += f'<button class="tab-button" onclick="openTab(event, \'{tab_id}\')" id="btn-{tab_id}">逆引き(rDNS)</button>\n'
        
        escaped_rdns = html.escape(rdns_raw)
        for h_str in rdns_hosts:
            escaped_h = html.escape(h_str)
            escaped_rdns = escaped_rdns.replace(escaped_h, f'<span class="json-hl">{escaped_h}</span>')
            
        cmd_str = f"resolver = dns.resolver.Resolver(configure=False); resolver.nameservers = ['8.8.8.8']; resolver.resolve(dns.reversename.from_address('{clean_ip}'), 'PTR')"
        host_list_str = "<br>".join([html.escape(h) for h in rdns_hosts]) if rdns_hosts else "取得なし"
        
        rdns_content = f"""
        <div id="{tab_id}" class="tab-content">
            <h1 class="theme-rdap" style="color: #424242; border-color: #424242;">DNS逆引き解決結果 (dnspython)</h1>
            <div class="description" style="background-color: #eceff1; border-color: #cfd8dc;">
                <strong>DNS逆引き(Reverse DNS) 解決記録：</strong><br>
                対象のIPアドレスに対してPython公式の国際標準ライブラリである <code>dnspython</code> を実行し、紐づくホスト名（PTRレコード）を取得した結果を示す。
            </div>
            <h2>対象IPアドレス及び取得結果</h2>
            <table>
                <tr><th>対象IPアドレス<br>(Target IP)</th><td><strong>{clean_ip}</strong></td></tr>
                <tr><th>取得日時<br>(Timestamp)</th><td><strong>{current_time_str}</strong></td></tr>
                <tr><th>取得ホスト名<br>(Resolved Hostnames)</th><td><strong>{host_list_str}</strong></td></tr>
            </table>
            <h2>内部実行クエリ (Python)</h2>
            <div class="raw-data" style="background-color: #263238; color: #eceff1; font-weight: bold; font-family: Consolas, monospace;">>>> {cmd_str}</div>
            <h2>実行結果 (ライブラリ出力)</h2>
            <div class="raw-data" style="font-family: Consolas, monospace;">{escaped_rdns}</div>
        </div>
        """
        contents_html += rdns_content

    # --- 10. 統合HTML構築 ---
    full_html = f"""
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>IP-OSINT - {clean_ip}</title>
        <style>
            body {{ font-family: 'Helvetica Neue', Arial, sans-serif; padding: 30px; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; }}
            .tab-container {{ margin-bottom: 20px; border-bottom: 2px solid #ccc; display: flex; }}
            .tab-button {{ background-color: #f8f9fa; border: 1px solid #ccc; border-bottom: none; outline: none; cursor: pointer; padding: 10px 20px; font-size: 16px; font-weight: bold; color: #555; border-radius: 5px 5px 0 0; margin-right: 5px; transition: 0.3s; }}
            .tab-button:hover {{ background-color: #e9ecef; }}
            .tab-button.active {{ background-color: #1e3a8a; color: white; border-color: #1e3a8a; }}
            .tab-content {{ display: none; animation: fadeEffect 0.4s; }}
            @keyframes fadeEffect {{ from {{opacity: 0;}} to {{opacity: 1;}} }}
            h1 {{ font-size: 24px; border-bottom: 2px solid; padding-bottom: 5px; text-align: center; margin-bottom: 30px;}}
            h1.theme-rdap {{ color: #1e3a8a; border-color: #1e3a8a; }}
            h1.theme-ipinfo {{ color: #00897b; border-color: #00897b; }}
            h1.theme-ip2proxy {{ color: #6a1b9a; border-color: #6a1b9a; }}
            h2 {{ font-size: 18px; margin-top: 30px; border-left: 4px solid #666; padding-left: 10px; }}
            .description {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; border: 1px solid #e9ecef; margin-bottom: 20px; font-size: 14px; text-align: justify; }}
            table {{ width: 100%; border-collapse: collapse; margin-bottom: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; font-size: 14px; vertical-align: top; }}
            th {{ background-color: #f2f2f2; width: 30%; }}
            .help-text {{ font-size: 12px; color: #666; display: block; margin-top: 4px; line-height: 1.4; }}
            .raw-data {{ font-family: monospace; background-color: #f4f4f4; padding: 15px; border-radius: 5px; white-space: pre-wrap; font-size: 12px; border: 1px solid #ccc; word-break: break-all; }}
            .json-hl {{ background-color: #fff59d; color: #c62828; font-weight: bold; border-radius: 2px; padding: 1px 3px; transition: 0.3s; -webkit-print-color-adjust: exact; print-color-adjust: exact; }}
            body.hide-hl .json-hl {{ background-color: transparent; color: inherit; font-weight: normal; padding: 0; }}
            body.hide-desc .description, body.hide-desc .help-text {{ display: none; }}
            body.compress-json .raw-data {{ white-space: normal; word-break: break-all; }}
            .controls {{ margin-bottom: 20px; text-align: right; background: #e3f2fd; padding: 10px; border-radius: 5px; border: 1px solid #bbdefb; }}
            .controls label {{ font-size: 14px; cursor: pointer; font-weight: bold; color: #1565c0; margin-right: 15px; display: inline-block; margin-bottom: 5px; }}
            .controls button {{ padding: 8px 16px; font-size: 14px; cursor: pointer; background-color: #1e3a8a; color: white; border: none; border-radius: 3px; transition: background 0.3s; margin-top: 5px; }}
            .controls button:hover {{ background-color: #1565c0; }}
            @media print {{
                body {{ padding: 0; max-width: 100%; }}
                .no-print, .tab-container {{ display: none !important; }}
                .tab-content {{ display: block !important; page-break-after: always; }}
                .tab-content:last-child {{ page-break-after: auto; }}
                .raw-data {{ page-break-inside: auto; }}
                .map-container iframe {{ width: 100% !important; }}
            }}
        </style>
    </head>
    <body>
        <div class="controls no-print">
            <div>
                <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-desc', !this.checked)"> 解説・ヘルプテキストを表示</label>
                <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-hl', !this.checked)"> JSONのハイライトを有効化</label>
                <label><input type="checkbox" onchange="document.body.classList.toggle('compress-json', this.checked)"> 生データ(JSON)を圧縮表示</label>
            </div>
            <button onclick="window.print()">🖨️ すべての情報を一括印刷</button>
        </div>
        
        <div class="tab-container no-print">
            {tabs_html}
        </div>
        
        {contents_html}

        <script>
            function openTab(evt, tabId) {{
                let i, tabcontent, tablinks;
                tabcontent = document.getElementsByClassName("tab-content");
                for (i = 0; i < tabcontent.length; i++) {{
                    tabcontent[i].style.display = "none";
                }}
                tablinks = document.getElementsByClassName("tab-button");
                for (i = 0; i < tablinks.length; i++) {{
                    tablinks[i].className = tablinks[i].className.replace(" active", "");
                }}
                document.getElementById(tabId).style.display = "block";
                if(evt) {{
                    evt.currentTarget.className += " active";
                }} else {{
                    document.getElementById("btn-" + tabId).className += " active";
                }}
            }}
            if('{first_tab_id}' !== 'None') {{ openTab(null, '{first_tab_id}'); }}
            window.onbeforeprint = function() {{
                let tabcontents = document.getElementsByClassName("tab-content");
                for (let j = 0; j < tabcontents.length; j++) {{ tabcontents[j].style.display = "block"; }}
            }};
            window.onafterprint = function() {{
                let activeTabId = "";
                let tablinks = document.getElementsByClassName("tab-button");
                for (let k = 0; k < tablinks.length; k++) {{
                    if (tablinks[k].className.indexOf("active") > -1) {{ activeTabId = tablinks[k].id.replace("btn-", ""); break; }}
                }}
                if (activeTabId) {{ openTab(null, activeTabId); }}
            }};
        </script>
    </body>
    </html>
    """
    return full_html

def generate_combined_html_report(target_results, report_opts=None):
    """複数の個別レポートを1つのHTMLファイル（目次付き）に統合する関数"""
    combined_body = ""
    toc_links = []
    common_style = ""
    
    for i, res in enumerate(target_results):
        target_ip = res.get('Target_IP', 'N/A')
        clean_ip = get_copy_target(target_ip)
        html = generate_individual_html_report(res, clean_ip, report_opts)
        if not html: continue
        
        # 1つ目のHTMLから共通スタイルを抽出
        if not common_style:
            style_match = re.search(r'<style>(.*?)</style>', html, re.DOTALL)
            if style_match: common_style = style_match.group(1)
            
        body_match = re.search(r'<body>(.*?)</body>', html, re.DOTALL)
        if body_match:
            bc = body_match.group(1)
            uid = f"_{i}"
            
            # 個別レポート用のコントロールパネルを削除
            bc = re.sub(r'<div class="controls no-print">.*?</button>\s*</div>', '', bc, flags=re.DOTALL)
            
            # 2件目以降は、長文になる解説（description）と補足（help-text）をHTMLから完全に削除して圧縮
            if i > 0:
                bc = re.sub(r'<div class="description".*?</div>', '', bc, flags=re.DOTALL)
                bc = re.sub(r'<span class="help-text">.*?</span>', '', bc, flags=re.DOTALL)
            
            # タブIDとJS関数名の置換（複数IP間でタブ切り替えが干渉しないようにUIDを付与）
            bc = bc.replace('id="tab-', f'id="tab{uid}-')
            bc = bc.replace('id="btn-tab-', f'id="btn-tab{uid}-')
            bc = bc.replace("openTab(event, 'tab-", f"openTab{uid}(event, 'tab{uid}-")
            bc = bc.replace('function openTab(evt, tabId)', f'function openTab{uid}(evt, tabId)')
            bc = bc.replace('openTab(null, ', f'openTab{uid}(null, ')
            bc = re.sub(r"openTab\{uid\}\(null,\s*'tab-(.*?)'\);", rf"openTab{uid}(null, 'tab{uid}-\1');", bc)
            
            # DOM取得スコープの限定
            bc = bc.replace('document.getElementsByClassName("tab-content")', f'document.getElementById("report-wrapper{uid}").getElementsByClassName("tab-content")')
            bc = bc.replace('document.getElementsByClassName("tab-button")', f'document.getElementById("report-wrapper{uid}").getElementsByClassName("tab-button")')
            
            # 個別印刷イベントの削除
            bc = re.sub(r'window\.onbeforeprint\s*=\s*function\(\)\s*\{.*?\};', '', bc, flags=re.DOTALL)
            bc = re.sub(r'window\.onafterprint\s*=\s*function\(\)\s*\{.*?\};', '', bc, flags=re.DOTALL)
            
            toc_links.append(f"<li><a href='#target{uid}' style='text-decoration: none; color: #1e3a8a; font-weight: bold;'>{clean_ip}</a></li>")
            
            # 重複するH2見出しを削除し、目次からのアンカー用divのみを配置
            combined_body += f"""
            <div id='target{uid}' style='margin-bottom: 60px; padding-bottom: 20px; border-bottom: 3px dashed #ccc; page-break-inside: avoid;'>
                <div id='report-wrapper{uid}'>{bc}</div>
            </div>
            """

    if not combined_body: return None
    
    # 統合用の追加CSSと印刷制御JS
    common_style += """
        body { background-color: #f0f2f5; }
        .main-container { background-color: white; padding: 40px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); max-width: 900px; margin: 0 auto; }
        .toc { background-color: #e3f2fd; padding: 20px; border-radius: 5px; margin-bottom: 40px; border: 1px solid #bbdefb; }
        .toc h2 { margin-top: 0; color: #1565c0; font-size: 22px; border-bottom: 2px solid #1565c0; padding-bottom: 5px; }
        .toc ul { column-count: 2; list-style-type: none; padding-left: 0; }
        .toc li { margin-bottom: 8px; padding: 5px; background: white; border-radius: 3px; border: 1px solid #ddd; text-align: center; }
        .toc li:hover { background: #bbdefb; }
        .combined-controls { background: #e3f2fd; padding: 15px; border-radius: 5px; border: 1px solid #bbdefb; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .combined-controls label { font-size: 14px; cursor: pointer; font-weight: bold; color: #1565c0; margin-right: 15px; display: inline-block; }
        .combined-controls button { padding: 10px 20px; font-size: 14px; font-weight: bold; background-color: #1e3a8a; color: white; border: none; border-radius: 5px; cursor: pointer; transition: 0.3s; }
        .combined-controls button:hover { background-color: #1565c0; }
        @media print {
            body { background-color: white; }
            .main-container { box-shadow: none; padding: 0; max-width: 100%; }
            .toc { page-break-after: always; }
        }
    """
    
    combined_js = """
    <script>
        window.onbeforeprint = function() {
            let tabcontents = document.getElementsByClassName("tab-content");
            for (let j = 0; j < tabcontents.length; j++) { tabcontents[j].style.display = "block"; }
        };
    </script>
    """

    full_combined_html = f"""
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Combined IP-OSINT Report</title>
        <style>{common_style}</style>
    </head>
    <body>
        <div class="main-container">
            <h1 style="text-align: center; color: #333; font-size: 28px; margin-bottom: 30px;">🔎 統合 IP-OSINT 調査レポート</h1>
            
            <div class="combined-controls no-print">
                <div>
                    <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-desc', !this.checked)"> 解説・ヘルプテキストを表示</label>
                    <label><input type="checkbox" checked onchange="document.body.classList.toggle('hide-hl', !this.checked)"> JSONのハイライトを有効化</label>
                    <label><input type="checkbox" onchange="document.body.classList.toggle('compress-json', this.checked)"> 生データ(JSON)を圧縮表示</label>
                </div>
                <button onclick="window.print()">🖨️ この統合レポートを一括印刷する</button>
            </div>

            <div class="toc no-print">
                <h2>📑 目次 (Target List)</h2>
                <ul>{''.join(toc_links)}</ul>
            </div>
            {combined_body}
        </div>
        {combined_js}
    </body>
    </html>
    """
    return full_combined_html